### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by noahsark769** [pocketsvg/PocketSVG#100]
There are several documentation issues with PocketSVG when documentation issues are turned on in Xcode (as is the default in Cocoapods):

<img width="289" alt="screen shot 2017-08-25 at 9 13 14 am" src="https://user-images.githubusercontent.com/1168853/29722461-c535423a-8975-11e7-919b-680ef354f9c2.png">

**Comment by noahsark769** [comment]
@arielelkin would you prefer to fix this yourself? I can also submit a quick pull request for it 👍

**Comment by arielelkin** [comment]
PRs are always welcome here 🙂, @noahsark769 . Go ahead and submit it and I'll work from it.

**Comment by noahsark769** [comment]
Opened #101, thanks!

**Comment by arielelkin** [comment]
fixed via https://github.com/pocketsvg/PocketSVG/pull/101
