### ISSUE TITLE
Some of the SVGs not loading correctly

### ISSUE THREAD

**Issue by AdilAnwerTrafficDigital** [pocketsvg/PocketSVG#104]
Hi

I am working in my office application and we are downloading svgs from our api and using it.

But the problem is that our svgs have multiple colors but these colors not loading. Instead it showing only black color in whole svg.

Please help me by giving the solution.

**Comment by fjolnir** [comment]
Please help me by giving me an example of an svg that causes it to fail.

**Comment by fjolnir** [comment]
Closing for now, will reopen if this turns out to be a bug.
