### ISSUE TITLE
How can I render a drawing from SVG Path

### ISSUE THREAD

**Issue by sriteja25** [pocketsvg/PocketSVG#108]
I have a string of SVG path coming up from Server, can I directly use this string to render the drawing on a view ? I tried looking into document but did not find what exactly I was looking for

NSString *path = "M 693 506 C 693 502 693 493 697.5 480.5M 697.5 480.5 C 702 468 712 449 723 432M 723 432 C 734 415 749 396 761.5 380.5M 761.5 380.5 C 774 365 780 359 796 343M 796 343 C 812 327 827 315 839.5 304M 839.5 304 C 852 293 865 287 871 282M 871 282 C 877 277 890 271 893 271M 893 271 C 896 271 909 271 915 271M 915 271 C 921 271 934 271 945 271M 945 271 C 956 271 971 271 983.5 271M 983.5 271 C 996 271 1003 271 1009 274M 1009 274 C 1015 277 1024 280 1027.5 283.5M 1027.5 283.5 C 1031 287 1034 299 1034 300.5M 1034 300.5 C 1034 302 1034 318 1034 324M 1034 324 C 1034 330 1034 340 1034 351M 1034 351 C 1034 362 1034 374 1034 386.5M 1034 386.5 "

**Comment by arielelkin** [comment]
You can pass that string to `CGPathsFromSVGString`, otherwise you can pass the SVG's entire XML to `SVGImageView`'s `init:svgSource` initializer.

**Comment by sriteja25** [comment]
Could you please throw a quick example of how exactly I can use the above mentioned solutions.

**Comment by arielelkin** [comment]
let url = NSBundle.mainBundle().URLForResource("svg_file_name", withExtension: "svg")!
    let svgImageView = SVGImageView(contentsOfURL: url)

This is an example from `SVGImageView.h` ;)

**Comment by sriteja25** [comment]
Actually I have a SVG path coming from server, I don't have any .svg extension files to load from. I have this sag string 

```NSString *path = "M 693 506 C 693 502 693 493 697.5 480.5M 697.5 480.5 C 702 468 712 449 723 432M 723 432 C 734 415 749 396 761.5 380.5M 761.5 380.5 C 774 365 780 359 796 343M 796 343 C 812 327 827 315 839.5 304M 839.5 304 C 852 293 865 287 871 282M 871 282 C 877 277 890 271 893 271M 893 271 C 896 271 909 271 915 271M 915 271 C 921 271 934 271 945 271M 945 271 C 956 271 971 271 983.5 271M 983.5 271 C 996 271 1003 271 1009 274M 1009 274 C 1015 277 1024 280 1027.5 283.5M 1027.5 283.5 C 1031 287 1034 299 1034 300.5M 1034 300.5 C 1034 302 1034 318 1034 324M 1034 324 C 1034 330 1034 340 1034 351M 1034 351 C 1034 362 1034 374 1034 386.5M 1034 386.5 "```

Can I use this string and render the drawing from it ?

**Comment by fjolnir** [comment]
That's not a valid svg, it's just a path attribute. You'll have to wrap it in an svg template like: `<?xml version="1.0" encoding="UTF-8"?><svg><path d="%@"/></svg>`

**Comment by HardikDG** [comment]
@sriteja25 Did you find any solution? I am also getting this type of path from the server and need to display the from the path.

**Comment by fjolnir** [comment]
@HardikDG I posted a solution right above your comment.

**Comment by HardikDG** [comment]
@fjolnir So I need to manually add the extra details for every SVG files? 
After I create that in which method should I pass that data to 'SVGImageView', 'CGPathsFromSVGString' or any other method?

**Comment by HardikDG** [comment]
@fjolnir From your suggestions, i have passed the data in the 'SVGImageView' and the SVG image is displayed.

- Does this library support transform and fill etc features?

<g transform="translate(0.000000,25.000000) scale(0.100000,-0.100000)"
fill="#000000" stroke="none">
I have this type data in the server SVG ,but when I try to add it in SVG template string, it stoped working in iOS. 

Can you please provide some details on how we can add this in the SVG String template?

**Comment by fjolnir** [comment]
That SVG works fine here

**Comment by HardikDG** [comment]
Sorry. I have rechecked it and in the debug, I found it was frame issue. The image frame is (0,0,0,0) from SVGImageView, After manual assignment of the frame, it started working.

Thanks for your time and efforts.

**Comment by sriteja25** [comment]
There is no init:svgSource property in the SVGImageVIew ? @arielelkin could you please check and reply on this ?

<html><body><svg height="738.0000000000001" width="697"><g><path d=" M 1158 218 C 1173 218 1361 902 1365.5 910M 1365.5 910 C 1370 918 1392 930 1431 938M 1431 938 C 1470 946 1502 946 1534.5 946M 1534.5 946 C 1567 946 1605 943 1631.5 936.5M 1631.5 936.5 C 1658 930 1683 921 1715.5 907M 1715.5 907 C 1748 893 1758 886 1775 875M 1775 875 C 1792 864 1805 852 1812.5 844M 1812.5 844 C 1820 836 1830 830 1834.5 822M 1834.5 822 C 1839 814 1842 811 1843.5 806.5M 1843.5 806.5 C 1845 802 1845 799 1845 796M 1845 796 C 1845 793 1845 793 1845 791 "  transform="translate(-1158, -218)" stroke="#ff6565" fill="none" stroke-width="10 px"></path></g></svg></body></html>

This is my string and as of now I am just using a web view to load content.

**Comment by fjolnir** [comment]
It’s on SVGBezierPath

**Comment by sriteja25** [comment]
Sorry but I could not sill figure out how to use could you please elaborate a bit

```NSString *path = "M 693 506 C 693 502 693 493 697.5 480.5M 697.5 480.5 C 702 468 712 449 723 432M 723 432 C 734 415 749 396 761.5 380.5M 761.5 380.5 C 774 365 780 359 796 343M 796 343 C 812 327 827 315 839.5 304M 839.5 304 C 852 293 865 287 871 282M 871 282 C 877 277 890 271 893 271M 893 271 C 896 271 909 271 915 271M 915 271 C 921 271 934 271 945 271M 945 271 C 956 271 971 271 983.5 271M 983.5 271 C 996 271 1003 271 1009 274M 1009 274 C 1015 277 1024 280 1027.5 283.5M 1027.5 283.5 C 1031 287 1034 299 1034 300.5M 1034 300.5 C 1034 302 1034 318 1034 324M 1034 324 C 1034 330 1034 340 1034 351M 1034 351 C 1034 362 1034 374 1034 386.5M 1034 386.5 "```

How can I convert it into Image / any other format to show as a drawing in my UIView ?

**Comment by sriteja25** [comment]
@HardikDG Can you leave your code, which you tried please ?

**Comment by HardikDG** [comment]
@sriteja25  I have used version 2.0 which still has `init:svgSource` method. 
Before this discussion with fjolnir, I have tried with the latest version but I was not able to do it with SVG string. so I have used the older version.

It will be great if @fjolnir or @arielelkin can include a sample string call in the example or readme file how to use it with the latest version

**Comment by fjolnir** [comment]
We have to expect some level of user competency since we can't just write out code for every use case in the readme.

in this case the code would be:
```objc
NSString *path = @"M 693 506 C 693 502 693 493 697.5 480.5M 697.5 480.5 C 702 468 712 449 723 432M 723 432 C 734 415 749 396 761.5 380.5M 761.5 380.5 C 774 365 780 359 796 343M 796 343 C 812 327 827 315 839.5 304M 839.5 304 C 852 293 865 287 871 282M 871 282 C 877 277 890 271 893 271M 893 271 C 896 271 909 271 915 271M 915 271 C 921 271 934 271 945 271M 945 271 C 956 271 971 271 983.5 271M 983.5 271 C 996 271 1003 271 1009 274M 1009 274 C 1015 277 1024 280 1027.5 283.5M 1027.5 283.5 C 1031 287 1034 299 1034 300.5M 1034 300.5 C 1034 302 1034 318 1034 324M 1034 324 C 1034 330 1034 340 1034 351M 1034 351 C 1034 362 1034 374 1034 386.5M 1034 386.5";

mySVGView.paths = [SVGBezierPath pathsFromSVGString:[NSString stringWithFormat:@"<svg><path stroke="#000" d=\"%@\"/></svg>", path]];
```
