### ISSUE TITLE
Multiple SVG objects in single view

### ISSUE THREAD

**Issue by HardikDG** [pocketsvg/PocketSVG#109]
I want to use the same SVG object at the multiple places in the main view. 

Should I create an individual SVG object for the each of the object?
If I use the same rendered object it only shows the last object on the screen. 

I want to use the same SVG object which is rendered once and display multiple time. How can I achieve it?

**Comment by arielelkin** [comment]
Hi @HardikDG 

We're going to need some more details in order to help you out. What do you refer to by an "SVG object"? An SVG file? Do you want to render the same SVG file on multiple places in which view?

**Comment by HardikDG** [comment]
I am creating an SVG from the SVG string. After rendering from that string I get an SVG object. Now I want to use it at multiple places in the single view. 

It is like where the user clicks on the screen I need to put this SVG object at that place in the main view. 

So my question is can I use the same SVG object?

**Comment by arielelkin** [comment]
yes.

**Comment by fjolnir** [comment]
Clarification: the “svg object” is just an array of bezier paths, and can be (re)used in the same way as a normal UIBezierPath
