### ISSUE TITLE
Wikipedia SVG's

### ISSUE THREAD

**Issue by zhunt11** [pocketsvg/PocketSVG#11]
I am trying to using PocketSVG with images I am getting from wikipedia.   http://commons.wikimedia.org/wiki/File:Blank_US_Map.svg

Unfortunately, I get an error: "Invalid Parameter count in M style token"

Do you know what this means and how can I fix it?

**Comment by arielelkin** [comment]
PocketSVG has been updated to v2.0.0! Multiple paths are supported now. Happy coding!
