### ISSUE TITLE
Add support for elliptical arcs

### ISSUE THREAD

**Issue by VishnuV02** [pocketsvg/PocketSVG#110]
### Steps to Reproduce the Problem
I am trying to load my .svg image into storyboard, but i am not receiving proper image in screen.
  1. Copied and added LockIcon.svg into project
  2. Set the property svgName as LockIcon in 
  3. Image displayed, but in console getting warning as "**Elliptical arcs not supported**"

### Specifications
[LockIcon.svg.zip](https://github.com/pocketsvg/PocketSVG/files/1739151/LockIcon.svg.zip)

  - PocketSVG Version: 2.0
  - Xcode Version: 9
  - iOS/macOS Version: 11.0

Please let me know the reason, as it is working perfectly in android phone.

**Comment by fjolnir** [comment]
As the error says, elliptical arcs are not supported.

**Comment by yarry** [comment]
#114

**Comment by yarry** [comment]
I've implemented in #114
