### ISSUE TITLE
Attributes are missing when using -[SVGBezierPath SVGRepresentation]

### ISSUE THREAD

**Issue by mciuba** [pocketsvg/PocketSVG#112]
### Steps to reproduce the issue

  1. Create a `SVGBezierPath` and set some SVG attributes 

```Swift
        let attributes: [String: Any] = [
            "stroke": "black",
            "stroke-width": "2",
            "fill": "transparent"
        ]
        let bezierPath = SVGBezierPath().settingSVGAttributes(attributes)
```
  
  2. Create and print SVG representation of the path

```Swift
let representation = bezierPath.svgRepresentation
print(representation)
```

**Expected result**: `path` has the specified attributes (stroke, fill, stroke-width) in the generated SVG
```XML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">
  <path stroke="black" fill="transparent" stroke-width="2.0" d=""/>

</svg>
```

**Actual result**: the attributes are missing
```XML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0">
  <path d=""/>

</svg>
```

### Has my issue been reported? 

No

### Specifications

  - PocketSVG Version: master (afd002b)
  - Xcode Version: 9.2
  - iOS/macOS Version: iOS 11.2

**Comment by arielelkin** [comment]
Thanks @mciuba, this looks good to me

@fjolnir, any thoughts ?
