### ISSUE TITLE
Colored SVG rendered as black

### ISSUE THREAD

**Issue by trusk89** [pocketsvg/PocketSVG#123]
### Steps to reproduce the issue

So I have an SVG at an URL somewhere online, and when I open it in my browser it has two colors, but when I load it with SwiftSVG it's all black. I don't want to apply fill or background colors because those are something else, but it it to have the exact colors that I see when I open the url in my browser.

Is there a setting I'm missing?

I've attached the one of my SVGs' contents here https://pastebin.com/CWAdKV2Q

Please include all relevant **code**, including **all** `PocketSVG` method calls made.
```
let svgImageView = SVGImageView(contentsOf: svgURL)
        svgImageView.frame = frame
        svgImageView.backgroundColor = UIColor(hexString: primaryColorString ?? "")
        svgImageView.contentMode = .scaleAspectFit
```

### Has my issue been reported? 

No

### Specifications

  - PocketSVG Version:  latest
  - Xcode Version: 9.3
  - iOS/macOS Version: 11.3

**Comment by fjolnir** [comment]
We don't support `<style>` tags.
