### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [str hasPrefix:@"#"]'

### ISSUE THREAD

**Issue by bakerbrooklyn** [pocketsvg/PocketSVG#125]
### Steps to reproduce the issue

  1. I try to render this SVG file: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg"
  2. Keep getting Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [str hasPrefix:@"#"]'

Please include all relevant **code**, including **all** `PocketSVG` method calls made.

### Has my issue been reported? 

My issue has been reported in the following [closed issues](https://github.com/pocketsvg/PocketSVG/issues?q=is%3Aissue+is%3Aclosed):

### Specifications

  - PocketSVG Version: HEAD
  - Xcode Version: 9.x
  - iOS/macOS Version: iOS 11.x

**Comment by arielelkin** [comment]
The assertion fails with this tag:  `<ellipse fill="url(#rg1)"` 

Unfortunately, we don't support the `url` parameter yet.

**Comment by ngthanhtan91** [comment]
is there any update for this feature? I got this issue two

**Comment by arielelkin** [comment]
We hope to work on this feature request, but unfortunately we cannot at this stage give you a timeframe for when it'll be done. Pull requests are always welcome, of course :-)

In the meantime, a workaround is to rewrite the `url` parameters in your SVG file.

**Comment by kritikaperiwal12** [comment]
I also get the same error, is there any solution for this? 
@arielelkin

**Comment by arielelkin** [comment]
As we said above, we don't support the url parameter yet unfortunately. We hope to work on this feature request, but unfortunately we cannot at this stage give you a timeframe for when it'll be done. Pull requests are always welcome, of course :-)

Would it help if we print an error message instead of throwing an exception ?

**Comment by fjolnir** [comment]
that would just make things fail unnoticed. URL loading is not an appropriate feature for a simple (de)serializer like pocketSVG. although `url(#rg1)` looks like some sort of file-local reference, so that limited support for that might be an acceptable PR. But not something I would spend time on.
