### ISSUE TITLE
Detect tap on parts of svg

### ISSUE THREAD

**Issue by pateldi1524** [pocketsvg/PocketSVG#126]
Is there any way we can detect a tap on each layer of SVG?

I am using this code for detect tap.

`override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {                                               
    let point = touches.first?.location(in: self.view)
    if let layer = self.view.layer.hitTest(point!) as? CAShapeLayer {
        if (layer.path?.contains(point!))! {
            layer.fillColor = UIColor.red.cgColor
        }
    }
}`

But this is not works when i have to resize image.

**Comment by arielelkin** [comment]
> Is there any way we can detect a tap on each layer of SVG?

It depends how your layers are superimposed.. Generally you will detect just the taps on the upmost layer. 

> But this is not works when i have to resize image.
Try adding a `UITouchRecognizer` to the view

**Comment by pateldi1524** [comment]
I want to change color of layer on which layer user tap.

**Comment by arielelkin** [comment]
the [code you pasted above](https://github.com/pocketsvg/PocketSVG/issues/126#issue-338515815) should work. 

If not, please provide an xcode project where I can reproduce the issue.

**Comment by pateldi1524** [comment]
Also when i render as a path, can't get the actual image in color.
[SVGDemo.zip](https://github.com/pocketsvg/PocketSVG/files/2166381/SVGDemo.zip)

**Comment by arielelkin** [comment]
Thanks. I saw your code. Again, it depends how your layers are superimposed. You're superimposing layers one on top of the other, so you will detect just the taps on the upmost layer.
