### ISSUE TITLE
iOS12 regression on pathsFromSVGString

### ISSUE THREAD

**Issue by libe** [pocketsvg/PocketSVG#128]
Hello, 

I am getting a regression when creating a CGPath from a SVG string with iOS12 (with iOS11 it works fine). It can be reproduced with the following data/code (a simple square).

Here's the svg:
```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="512.000000pt" height="512.000000pt" viewBox="0 0 512.000000 512.000000"
 preserveAspectRatio="xMidYMid meet">
<metadata>
</metadata>
<g transform="translate(0.000000,512.000000) scale(1.000000,1.000000)"
fill="#000000" stroke="none">
<path d="M21 256 l0 -235 235 0 235 0 0 235 0 235 -235 0 -235 0 0 -235z"/>
</g>
</svg>
```

### Steps to reproduce the issue

```objc
    NSString* svg = @"<?xml version=\"1.0\" standalone=\"no\"?> <!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 20010904//EN\" \"http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd\"> <svg version=\"1.0\" xmlns=\"http://www.w3.org/2000/svg\" width=\"512.000000pt\" height=\"512.000000pt\" viewBox=\"0 0 512.000000 512.000000\" preserveAspectRatio=\"xMidYMid meet\"> <metadata> </metadata> <g transform=\"translate(0.000000,512.000000) scale(1.000000,1.000000)\" fill=\"#000000\" stroke=\"none\"> <path d=\"M21 256 l0 -235 235 0 235 0 0 235 0 235 -235 0 -235 0 0 -235z\"/> </g> </svg>";
    NSArray *paths = [SVGBezierPath pathsFromSVGString:svg];
    SVGBezierPath *firstPath = paths.firstObject;
    UIBezierPath *path = [UIBezierPath bezierPathWithCGPath:firstPath.CGPath];
    CGRect pathBounds = CGPathGetPathBoundingBox(path.CGPath);
    NSLog(@"PATH BOUNDS: %@", NSStringFromCGRect(pathBounds));
```

### Has my issue been reported? 

No.

### Results

With iOS 11 
PATH BOUNDS: {{21, 21}, {470, 470}}

With iOS 12
PATH BOUNDS: {{0, 0}, {491, 491}}
 
If I dump the control points I can see that under iOS12 there's the origin added as control point while this is not happening under iOS11:

iOS12
```
  Bounds: {{0, 0}, {491, 491}}
  Control Point Bounds: {{0, 0}, {491, 491}}
    0.000000 0.000000 moveto
    21.000000 256.000000 moveto
    21.000000 21.000000 lineto
    256.000000 21.000000 lineto
    491.000000 21.000000 lineto
    491.000000 256.000000 lineto
    491.000000 491.000000 lineto
    256.000000 491.000000 lineto
    21.000000 491.000000 lineto
    21.000000 256.000000 lineto
    closepath
```
iOS11
```
Bounds: {{21, 21}, {470, 470}}
  Control Point Bounds: {{21, 21}, {470, 470}}
    21.000000 256.000000 moveto
    21.000000 21.000000 lineto
    256.000000 21.000000 lineto
    491.000000 21.000000 lineto
    491.000000 256.000000 lineto
    491.000000 491.000000 lineto
    256.000000 491.000000 lineto
    21.000000 491.000000 lineto
    21.000000 256.000000 lineto
    closepath
```

### Specifications

  - PocketSVG Version: 2.4.0
  - Xcode Version: 10.0 GM
  - iOS/macOS Version: iOS 12 GM

Thanks for any feedback,
Libe

**Comment by libe** [comment]
Thanks for the insight. I tried to remove the line and it seems to be working. It looks like that under iOS12 two consecutive moveto operations are not collapsed into one...as it happens under iOS11.

**Comment by arielelkin** [comment]
Hi folks, thanks for raising this. 

I think that line can be removed, unless @fjolnir has more thoughts?

**Comment by 008v** [comment]
I had the same problem. Got an incorrect boundingbox.

**Comment by 008v** [comment]
```
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        let path = UIBezierPath()
        let origin = CGPoint(x: 0, y: 0)
        let topLeft = CGPoint(x: 100, y: 100)
        let topRight = CGPoint(x: 200, y: 100)
        let bottomRight = CGPoint(x: 200, y: 200)
        let bottomLeft = CGPoint(x: 100, y: 200)
        path.move(to: origin)
        path.move(to: topLeft)
        path.addLine(to: topRight)
        path.addLine(to: bottomRight)
        path.addLine(to: bottomLeft)
        path.addLine(to: topLeft)
        
        let shapeLayer = CAShapeLayer()
        shapeLayer.path = path.cgPath
        shapeLayer.fillColor = UIColor.blue.cgColor
        
        view.layer.addSublayer(shapeLayer)
        
        print(path.cgPath.boundingBox)        
    }
}
```

iOS 11 (100.0, 100.0, 100.0, 100.0)

iOS 12 (0.0, 0.0, 200.0, 200.0)

**Comment by fjolnir** [comment]
Thanks for the datapoint.

**Comment by 008v** [comment]
> I am able to reproduce this and the cause seems to be in https://github.com/pocketsvg/PocketSVG/blob/master/SVGEngine.mm line 496.
> If you comment the line CGPathMoveToPoint(_path, NULL, 0, 0); everything seems to be fine.
> Tested on iOS 11 and 12, not sure what was the purpose of that line, it looks like a bug workaround for something.
> 
> Maybe the author knows more.

This method implicitly ends the current subpath (if any) .For many path operations, you must call this method before issuing any commands that cause a line or curve segment to be drawn.

https://developer.apple.com/documentation/uikit/uibezierpath/1624343-move

**Comment by lukas2** [comment]
I'm also seeing this problem.

There's also a mention of this problem at Apple forums: https://forums.developer.apple.com/thread/108631

**Comment by cristian1980** [comment]
> There's also a mention of this problem at Apple forums: https://forums.developer.apple.com/thread/108631

I posted that, but I have no hopes for an answer.

> This method implicitly ends the current subpath (if any) .For many path operations, you must call this method before issuing any commands that cause a line or curve segment to be drawn.

all SVG resources I've seen already start with a Move command for example:
`<path d="M 186.10383,12.92399 L 310.51723,12.92399 C 313.80458,12.92399 316.5....`

That M is actually a move command, the issue is that we have too many move commands not too few.

However I found that with CGPathMoveToPoint(_path, NULL, 0, 0) commented out I am now getting a warning:

> CGPathGetCurrentPoint: no current point.

Which is probably the reason CGPathMoveToPoint(_path, NULL, 0, 0) was added.
This is happening here:
```
void pathDefinitionParser::appendMoveTo()
{
    if(_operands.size()%2 != 0) {
        NSLog(@"*** Error: Invalid parameter count in M style token");
        return;
    }

    for(NSUInteger i = 0; i < _operands.size(); i += 2) {
        CGPoint currentPoint = CGPathGetCurrentPoint(_path);
        CGFloat x = _operands[i+0] + (_cmd == 'm' ? currentPoint.x : 0);
        CGFloat y = _operands[i+1] + (_cmd == 'm' ? currentPoint.y : 0);

        if(i == 0)
            CGPathMoveToPoint(_path, NULL, x, y);
        else
            CGPathAddLineToPoint(_path, NULL, x, y);
    }
}
```
Calling CGPathGetCurrentPoint on an empty path is documented by apple and should return (0,0) no mention is made about a warning...

To fix that warning path should be checked if is empty before calling CGPathGetCurrentPoint on it.
Something like this:
```
void pathDefinitionParser::appendMoveTo()
{
    if(_operands.size()%2 != 0) {
        NSLog(@"*** Error: Invalid parameter count in M style token");
        return;
    }

    for(NSUInteger i = 0; i < _operands.size(); i += 2) {
        CGPoint currentPoint = CGPointMake(0, 0);
        if(!CGPathIsEmpty(_path))
            currentPoint = CGPathGetCurrentPoint(_path);
        CGFloat x = _operands[i+0] + (_cmd == 'm' ? currentPoint.x : 0);
        CGFloat y = _operands[i+1] + (_cmd == 'm' ? currentPoint.y : 0);

        if(i == 0)
            CGPathMoveToPoint(_path, NULL, x, y);
        else
            CGPathAddLineToPoint(_path, NULL, x, y);
    }
}
```

**Comment by cristian1980** [comment]
> Removing it should be fine, I wonder about paths that start with a curve to etc though. Might need to add some code to make them default to starting at 0,0

All the functions that draw paths in PocketSVG seem  to use CGPathGetCurrentPoint to get the starting point, see:
```
    void appendMoveTo();
    void appendLineTo();
    void appendCubicCurve();
    void appendShorthandCubicCurve();
    void appendQuadraticCurve();
    void appendShorthandQuadraticCurve();
    void appendArc();
```
Calling [CGPathGetCurrentPoint](https://developer.apple.com/documentation/coregraphics/1411132-cgpathgetcurrentpoint) on an empty path will return (0,0) however you will get a warning(which is not documented) so there will be no problems except for that warning.

**Comment by 008v** [comment]
所以这个问题要怎么解决？尤其是注释了以后，产生了一大堆的警告。

**Comment by fjolnir** [comment]
By only adding a move if the first command in the path is not a move.

**Comment by arielelkin** [comment]
I've made a PR based on the work by @008v and @nicolasmuller that adds a conditional check for iOS 12: https://github.com/pocketsvg/PocketSVG/pull/130

Please comment on it if you have any objections to merging it while the wider CG issue gets solved. 

@fjolnir

**Comment by arielelkin** [comment]
Closed https://github.com/pocketsvg/PocketSVG/pull/130 as https://github.com/pocketsvg/PocketSVG/issues/128#issuecomment-425224367 is a much better solution. Unfortunately I don't have much time right now to fix it, but PRs are welcome!

**Comment by noahsark769** [comment]
Just adding that I'm seeing this regression in iOS 12 as well. @fjolnir are you going to work on a PR for this? If not, I'm happy to (though I don't have too much experience with SVG)

**Comment by fjolnir** [comment]
I don't have the time right now, so it would be great if you could do it!
