### ISSUE TITLE
Overriding "fill=none" and "stroke=none" with SVGLayer fillColor and strokeColor

### ISSUE THREAD

**Issue by dstranz** [pocketsvg/PocketSVG#132]
### Steps to reproduce the issue

  1. Let's assume that we have an SVG with following polyline 
```swift
let svg = "...<polyline xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" stroke=\"#0074d9\" stroke-width=\"6\" points=\"7, 81 14, 89 21, 82 28, 92 35, 93 42, 74 49, 53 56, 49 63, 49 70, 46 77, 53 84, 51 91, 71 98, 100 105, 86 112, 87 119, 75 126, 69 133, 29 140, 5 147, 12 154, 7 161, 11 168, 22 175, 44 182, 69 189, 61 196, 47 203, 48 210, 11 217, 23 224, 42 231, 34 238, 29 245, 28 252, 36 259, 38 266, 50 273, 50 280, 35 287, 34 294, 34 301, 30 308, 26 315, 27 322, 21 329, 19 336, 20 \"> </polyline>..."
```

  2. We are creating layers with following code 
```swift
let paths = SVGBezierPath.paths(fromSVGString: svg)` to create paths
let layer = SVGLayer()
layer.paths = paths
```

3. We want to change fillColor or strokeColor of SVG. We have convenient properties in `SVGLayer`:
```swift
layer.fillColor = .red
layer.strokeColor = .blue
```

### Expectation
![expected_result](https://user-images.githubusercontent.com/96502/46723572-75d78300-cc78-11e8-9917-aa074acd38b2.png)
We would like to override colors from SVG file, but only for those paths that already had any `fillColor` or `strokeColor`. 

### Reality
![reality](https://user-images.githubusercontent.com/96502/46723571-75d78300-cc78-11e8-806b-945f9a8c934f.png)

```objc
        layer.fillColor   = _fillColor
                         ?: (__bridge CGColorRef)path.svgAttributes[@"fill"]
                         ?: [[PSVGColor blackColor] CGColor];
        layer.strokeColor = _strokeColor
                         ?: (__bridge CGColorRef)path.svgAttributes[@"stroke"];
```
Above code will set fillColor for layer with `fill=none` and `strokeColor` for layers with `stroke=none`. As the result we are getting corrupted SVG layers.

It's important if you want to draw for example a chart with line (one layer, fill=none) and color below line (second layer, fill=someColor).

What I would suggest will be to set `layer.fillColor` only for layers that hasn't `fill=none`, and `layer.strokeColor` only for layers that hasn't `stroke=none`.

What do you think?

**Comment by fjolnir** [comment]
Should probably map to clearColor

**Comment by dstranz** [comment]
@fjolnir It could be clearColor, but it's also possible to set CAShapeLayer's `fillColor` as `nil`. 

Which option will be better? I could prepare PR then.

**Comment by dstranz** [comment]
@fjolnir I probably described this issue in wrong way.

It is set as black with alpha 0 currently in:
```objc
 if([attrs[attr] isEqual:@"none"]) {
                CGColorSpaceRef const colorSpace = CGColorSpaceCreateDeviceRGB();
                attrs[attr] = (__bridge_transfer id)CGColorCreate(colorSpace, (CGFloat[]) { 1, 1, 1, 0 });
                CFRelease(colorSpace);
            }
```
It's quite fine, however we can also use `fillColor=nil` that may be a better translation of `none`

### Steps to reproduce the issue

1 and 2 as in Issue description
3. We want to change fillColor or strokeColor of SVG. We have convenient properties in `SVGLayer`:
```swift
layer.fillColor = .red
layer.strokeColor = .blue
```

### Expectation
![expected_result](https://user-images.githubusercontent.com/96502/46723572-75d78300-cc78-11e8-9917-aa074acd38b2.png)
We would like to override colors from SVG file, but only for those paths that already had any `fillColor` or `strokeColor`. 

### Reality
![reality](https://user-images.githubusercontent.com/96502/46723571-75d78300-cc78-11e8-806b-945f9a8c934f.png)

```objc
        layer.fillColor   = _fillColor
                         ?: (__bridge CGColorRef)path.svgAttributes[@"fill"]
                         ?: [[PSVGColor blackColor] CGColor];
        layer.strokeColor = _strokeColor
                         ?: (__bridge CGColorRef)path.svgAttributes[@"stroke"];
```
Above code will set fillColor for layer with `fill=none` and `strokeColor` for layers with `stroke=none`. As the result we are getting corrupted SVG layers.

It's important if you want to draw for example a chart with line (one layer, fill=none) and color below line (second layer, fill=someColor).

What I would suggest will be to set `layer.fillColor` only for layers that hasn't `fill=none`, and `layer.strokeColor` only for layers that hasn't `stroke=none`.

What do you think?

**Comment by fjolnir** [comment]
> We would like to override colors from SVG file, but only for those paths that already had any fillColor or strokeColor.

This is not what the property was intended for. It was just for filling paths without any color information. Such as simple icons.

If you want to manually override on a path by path basis, you can just set your own fill using `-[SVGBezierPath pathBySettingSVGAttributes:]`

**Comment by dstranz** [comment]
@fjolnir OK, thank for the info! :)
