### ISSUE TITLE
SVG displaying error

### ISSUE THREAD

**Issue by lukaszkrystek** [pocketsvg/PocketSVG#135]
### Steps to reproduce the issue

  1. Just open attached files using PocketSVG

Some SVG files don't display properly.
They display properly in browsers (Chrome, Safari). However, using PocketSVG
(iOS) they do not display correctly.
Please see attached files.

### Specifications

  - PocketSVG Version: 2.4.1 - newest
  - Xcode Version: Version 10.0 (10A255) - newest 
  - iOS/macOS Version: iOS 12.0.1 - newest

**Comment by arielelkin** [comment]
Hi there @lukaszkrystek 
Looks like you forgot to attach the files! Could you please copy and paste the xml of the SVGs?
Cheers

**Comment by lukaszkrystek** [comment]
Hi @arielelkin 

Sorry, yes I forgot. I attached now.
Please see them.

[SVG_not_supported.zip](https://github.com/pocketsvg/PocketSVG/files/2522954/SVG_not_supported.zip)

**Comment by marinofaggiana** [comment]
@arielelkin try with this ...

<svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" version="1.1" viewBox="0 0 16 16"><path d="m7.9992 0.999a6.9993 6.9994 0 0 0 -6.9992 6.9996 6.9993 6.9994 0 0 0 6.9992 6.9994 6.9993 6.9994 0 0 0 3.6308 -1.024c0.86024 0.34184 2.7871 1.356 3.2457 0.91794 0.47922-0.45765-0.56261-2.6116-0.81238-3.412a6.9993 6.9994 0 0 0 0.935 -3.4814 6.9993 6.9994 0 0 0 -6.9991 -6.9993zm0.0008 2.6611a4.34 4.3401 0 0 1 4.34 4.3401 4.34 4.3401 0 0 1 -4.34 4.3398 4.34 4.3401 0 0 1 -4.34 -4.3398 4.34 4.3401 0 0 1 4.34 -4.3401z" stroke-width="0.14"/></svg>

**Comment by arielelkin** [comment]
* `Europe` is displaying fine
* `Europe_states_reduced` has a `style` attribute which we don't support.
* `Greece` has an `rgb` value that doesn't begin with `#`
* `icon_invite` has a `clipPath` attribute which we don't support. 

Support for these attributes would be a great thing, as many users would like it (see for example https://github.com/pocketsvg/PocketSVG/issues/123). 

Your PRs are always welcome 😀
