### ISSUE TITLE
Rebuild PocketSVG is not enable bitcode: Failed to verify bitcode in PocketSVG.framework/PocketSVG: error: Bundle only contains bitcode-marker /var/folders/rh/qx_0gvzn6kzbqjvvbbh66t080000gn/T/IDEDistributionOptionThinning.1Wa/Payload/CutCopyPaste.app/Frameworks/PocketSVG.framework/PocketSVG (armv7)

### ISSUE THREAD

**Issue by tikamchandrakar18** [pocketsvg/PocketSVG#138]
### Steps to reproduce the issue

  1. 
  1.
  1.

Please include all relevant **code**, including **all** `PocketSVG` method calls made.

### Has my issue been reported? 

My issue has been reported in the following [closed issues](https://github.com/pocketsvg/PocketSVG/issues?q=is%3Aissue+is%3Aclosed):

### Specifications

  - PocketSVG Version: 
  - Xcode Version:
  - iOS/macOS Version:

**Comment by arielelkin** [comment]
The issue's "steps to reproduce" and "specifications" are empty. Maybe you opened this by mistake? If not, feel free to fill that in and re-open 😁
