### ISSUE TITLE
Modifying properties on SVG

### ISSUE THREAD

**Issue by vaibhav-jhaveri-ds** [pocketsvg/PocketSVG#145]
Here's the SVG string that I get using ```bezierPath.svgRepresentaion```
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="43" height="43">
  <path d="M8,25.5C8,15.8,15.9,7.9,25.6,8c9.7,0,17.5,7.9,17.5,17.6C43,35.2,35.1,43,25.5,43C15.8,43,8,35.2,8,25.5z" d="M8,25.5C8,15.8,15.9,7.9,25.6,8C35.3,8,43.1,15.9,43.1,25.6C43,35.2,35.1,43,25.5,43C15.8,43,8,35.2,8,25.5Z"/>
```

I want to modify the `height` and `width` property of the SVG tag

How do I do it? 

I tried using ```bezierPath.settingSVGAttributes(["height": "75", "width": "75"])```  but it didn't work

### Specifications

  - PocketSVG Version: 2.4.2
  - Xcode Version: 10.1
  - iOS/macOS Version: 12.1

**Comment by arielelkin** [comment]
If you want to modify the tags in the SVG file, I recommend you use an XML editing library. Otherwise you can set the height and width directly on the CALayer or UIImageView that results from PocketSVG.
