### ISSUE TITLE
Line Width/Thickness for SVGImageView

### ISSUE THREAD

**Issue by vaibhav-jhaveri-ds** [pocketsvg/PocketSVG#147]
Please add a feature to add/edit line width/thickness to a SVGImageView object

**Comment by arielelkin** [comment]
you want to do that by generating a CALayer from an SVG and manipulating those properties directly there. See https://github.com/pocketsvg/PocketSVG/blob/master/Demos/Demo-iOS/Demo-iOS/IcelandicViewController.swift#L28
