### ISSUE TITLE
CGPathGetCurrentPoint: no current point emitted

### ISSUE THREAD

**Issue by robaho** [pocketsvg/PocketSVG#150]
When using PocketSVG, it continually emits 'no current point'.

I believe the problem is the following code is lines 576-578 in SVGEngine.mm

```
        CGPoint currentPoint = CGPathGetCurrentPoint(_path);
        CGFloat x = _operands[i+0] + (_cmd == 'm' ? currentPoint.x : 0);
        CGFloat y = _operands[i+1] + (_cmd == 'm' ? currentPoint.y : 0);
```

in pathDefinitionParser::appendMoveTo()

I believe the code should be changed to be:

```
        CGPoint currentPoint = _cmd == 'm' && !CGPathIsEmpty(_path) ? CGPathGetCurrentPoint(_path) : CGPointZero;
        CGFloat x = _operands[i+0] + currentPoint.x;
        CGFloat y = _operands[i+1] + currentPoint.y;
```

which will avoid calling CGPathGetCurrentPoint() when the path is most likely empty, and wouldn't be used anyway.

**Comment by robaho** [comment]
I think this is related to issue #133

**Comment by arielelkin** [comment]
Hi @robaho 
Could you please provide steps to reproduce this issue?

**Comment by DanielGibbsNZ** [comment]
I'm experiencing this issue as well. I can reproduce it with the following code and SVG:

```
let url = Bundle.main.url(forResource: "example", withExtension: "svg")
let svgLayer = SVGLayer(contentsOf: url!)
```

*example.svg*

```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M25,50 C25,100 150,100 150,50 Z" />
</svg>
```

**Comment by robaho** [comment]
I gave the PR that fixes it. And the previous poster has given the test case. I would suggest applying the PR.

**Comment by fjolnir** [comment]
I don't see any PR originating from you @robaho

**Comment by robaho** [comment]
I’m sorry, I had a PR but didn’t submit it - the code changes I show in the comment are what is needed. I will see if I can resurrect the PR.

**Comment by arielelkin** [comment]
fixed via https://github.com/pocketsvg/PocketSVG/pull/173
