### ISSUE TITLE
SVGLayer becomes pixelated when zoomed

### ISSUE THREAD

**Issue by sebastianludwig** [pocketsvg/PocketSVG#152]
### Steps to reproduce the issue

  1. Use the following snippet as `viewDidLoad` in `IcelandicViewController`
  1. Run the demo and choose "Icelandic"
  1. Zoom in

```
override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        
        let svgURL = Bundle.main.url(forResource: "iceland", withExtension: "svg")!
        let svgLayer = SVGLayer(contentsOf: svgURL)
        icelandicView.layer.addSublayer(svgLayer)
        
        svgLayer.bounds = CGRect(x: 0, y: 0, width: svgLayer.preferredFrameSize().width, height: svgLayer.preferredFrameSize().height)
        icelandicView.frame = svgLayer.bounds
        
        let scrollview = UIScrollView(frame: view.bounds)
        scrollview.maximumZoomScale = 50.0
        scrollview.minimumZoomScale = 0.5
        
        scrollview.contentSize = svgLayer.bounds.size
        
        scrollview.delegate = self
        
        scrollview.addSubview(icelandicView)
        
        view.addSubview(scrollview)
    }
```

One great advantage of vector images is, that they can be zoomed without blurring/pixelating. However PocketSVG/SVGLayer does not yield this benefit, because [rasterization is enabled](https://github.com/pocketsvg/PocketSVG/blob/master/SVGLayer.m#L23-L26).

The origin of this goes back to the implementation of [`SVGImageView`](https://github.com/pocketsvg/PocketSVG/commit/f89a30bac7d868f6c97b4f45791b04e2b8a476e2#diff-6902758676ca2c01868cdf1db89a617c) in 2014, unfortunately without explanation _why_ rasterization was enabled.

Do you guys remember? If so, could you maybe a comment about it in the readme? Otherwise I suggest leaving `shouldRasterize` on its default value `NO`.

**With rasterization:**
![shouldRasterize](https://user-images.githubusercontent.com/1715010/54162309-5629ce00-4455-11e9-968e-99619a1f9b7d.png)

**Without rasterization:**
![shouldNotRasterize](https://user-images.githubusercontent.com/1715010/54162308-55913780-4455-11e9-91e8-3d08623c7632.png)

**Comment by fjolnir** [comment]
I made it on by default for performance reasons. It's easy to disable if needed.
