### ISSUE TITLE
SVG image rendering issue 

### ISSUE THREAD

**Issue by kritikaperiwal12** [pocketsvg/PocketSVG#155]
I have a SVG image file and the task is to parse that image. I am able to show image by parsing different layers of image using Pocket SVG but vales of text tag is not showing. Main issue and the task of parse SVG that is pending is text not appearing on the SVG only.
I also try to use different framework i.e. SVGKit, Swift SVG. But in both these caes i am not able to parse the different layer of image. But using Pocket SVG i am able to parse the SVG. Issue is of text only.
Can anyone help me.

Link of SVG image file: https://drive.google.com/file/d/1kdoApJ606kCXd8tfYqWGjAqs_BTOhY94/view?usp=sharing

**Comment by arielelkin** [comment]
Sorry but we don't support text tags.
