### ISSUE TITLE
Which SVG Profile it support?

### ISSUE THREAD

**Issue by MilTravelerIos** [pocketsvg/PocketSVG#156]
Hi,

      I want to know that which SVG profile (SVG1.0, SVG1.1, SVG Tiny1.1, SVG Tiny 1.1+, SVG Basic 1.1, SVG Tiny 1.2) PocketSVG support?

Thanks

**Comment by fjolnir** [comment]
Most likely a small subset of svg tiny. The readme has a list of supported tags.
