### ISSUE TITLE
Assertion failure in hexTriplet

### ISSUE THREAD

**Issue by smhk** [pocketsvg/PocketSVG#161]
unfortunately I got a

Assertion failure in hexTriplet::hexTriplet(NSString *__strong)(), /Users/jpm/Desktop/PocketSVG-master/SVGEngine.mm:888

that's in 
hexTriplet::hexTriplet(NSString *str)
...
NSCParameterAssert([str hasPrefix:@"#"]);

Could be due to a gradient?  Bummer...

**Comment by arielelkin** [comment]
Could you please provide steps to reproduce this?

**Comment by smhk** [comment]
will do, I'll get an example file, thanks!

**Comment by smhk** [comment]
@arielelkin , thanks, there's the test file.  I have found another one that throws the same error (it;'s a corporate logo, I could email it if you wish)

not sure what the issue could be!  the TIGER does indeed have gradients so I guess that is not the problem as such.

**Comment by arielelkin** [comment]
Thanks for sending this through. I suspect it's because the colours are expressed as RGB values rather than hex.  Can you try this format:`fill="#cc7226"` rather than `rgb(0, 38, 245)`

**Comment by arielelkin** [comment]
Closing as I haven't heard back, but feel free to reopen if the problem persists.

**Comment by smhk** [comment]
Sorry, so busy, will get to it !!!!!!!!

**Comment by AKogut91** [comment]
Hi I have some strange crash
*** Assertion failure in hexTriplet::hexTriplet(NSString *__strong)(), SVGEngine.mm:904

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [str hasPrefix:@"#"]'

**Comment by arielelkin** [comment]
this is probably due to a colour being expressed as an RGB value rather than hex.
