### ISSUE TITLE
Can't compile PocketSVG pod on Xcode 11 beta 5

### ISSUE THREAD

**Issue by danicoello** [pocketsvg/PocketSVG#163]
I am trying to compile my iOS app with PocketSVG on Xcode 11.0 beta 5 to test iOS 13 compilation but then I get this error:

```
error: Unexpected duplicate tasks:
1) Target 'PocketSVG' (project 'Pods') has copy command from '/Users/user/MyProject/Pods/PocketSVG/SVGColors.plist' to '/Users/user/Library/Developer/Xcode/DerivedData/MyApp-dygpybssjqqnrfggnfusoynmueff/Build/Products/MyTarget-iphonesimulator/PocketSVG/PocketSVG.framework/SVGColors.plist'
2) Target 'PocketSVG' (project 'Pods') has copy command from '/Users/user/MyProject/Pods/PocketSVG/SVGColors.plist' to '/Users/user/Library/Developer/Xcode/DerivedData/MyApp-dygpybssjqqnrfggnfusoynmueff/Build/Products/MyTarget-iphonesimulator/PocketSVG/PocketSVG.framework/SVGColors.plist'
```

When I remove PocketSVG dependency all other pods are compiling successfully so I supposed this compilation problem is related to PocketSVG pod itself.

### Specifications

  - PocketSVG Version: Last commit 409141238c95abe54cbec82f6b95ea71d47baf39
  - Xcode Version: Xcode 11.0 beta 5 (11M382q)
  - iOS/macOS Version: Version 10.14.5

Do you have any ideas what is happening?

**Comment by arielelkin** [comment]
I will wait for Xcode 11 to come out of beta to test this out, but in the meantime can you please let me know if this problem also occurs if you integrate pocketsvg as a pod within a completely new xcode 11 project?

**Comment by danicoello** [comment]
I have created a very basic Single View Project with a PocketSVG import and it compiles on Xcode 11.
It is strange that, with Xcode 10.2.1 my project compiles perfectly and I haven't change anything to the project. Other pods compiles without any problem so I think it may be something related to PocketSVG. Any ideas?

**Comment by alexanderkhitev** [comment]
I faced the same problem

**Comment by HanSJin** [comment]
please fix it.. :(

**Comment by gaidukov-nikita** [comment]
As a workaround you could select Pods-> PocketSVG target -> Build Phases -> And drag SVGColors.plist file from `Compile Sources` to `Copy Bundle Resources`.

**Comment by alexanderkhitev** [comment]
@arielelkin is 2.5.0 version available?

**Comment by arielelkin** [comment]
Yes, it's now available using Cocoapods, and includes support for Xcode 11. I'm therefore closing this, feel free to reopen if there are issues.
