### ISSUE TITLE
Some files don't support

### ISSUE THREAD

**Issue by alexanderkhitev** [pocketsvg/PocketSVG#165]
I did exported new svg files from Sketch Version 57.1 (83088), but they do not work, I tried using them in other frameworks or Google Chrome, and they work well there. How to fix this problem? I made a demo project in which I added our file and pasted it into the `GrayscaleTigerViewController`, also in the archive you will find this file separately.

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/12511909/63465622-b1cf9d00-c472-11e9-9971-23b659bbc9f3.png">

[Archive.zip](https://github.com/pocketsvg/PocketSVG/files/3527164/Archive.zip)

**Comment by alexanderkhitev** [comment]
I checked here https://validator.w3.org/check and got following result 

> This document was successfully checked as SVG 1.1 + URL + HTML + MathML 3.0!

**Comment by arielelkin** [comment]
Hi @alexanderkhitev 

Thanks for reporting this, either I or @fjolnir will take a look soon.

**Comment by alexanderkhitev** [comment]
@arielelkin thank you so much!

**Comment by fjolnir** [comment]
Yeah, Sketch is using `<defs` followed by `<use` directives, as well as `<mask`; none of which are supported. I hope there's a way to get it to output more simply. What does your .sketch file look like?

**Comment by alexanderkhitev** [comment]
Hi @fjolnir ! thanks for quick response! I cannot send the original file from designer, but I can send file which contains only this mask. 

[Archive.zip](https://github.com/pocketsvg/PocketSVG/files/3536158/Archive.zip)

**Comment by alexanderkhitev** [comment]
Hey @fjolnir ! I installed [svgo-compressor](https://github.com/BohemianCoding/svgo-compressor), then used [svg-optimize](https://sketchmaster.com/svg-optimizer) and it works fine with PocketSVG

**Comment by fjolnir** [comment]
Great!
