### ISSUE TITLE
Rotate transform doesn't work 

### ISSUE THREAD

**Issue by alexanderkhitev** [pocketsvg/PocketSVG#167]
PocketSVG renders SVG file without rotation. 
[MaskRotation.svg.zip](https://github.com/pocketsvg/PocketSVG/files/3538273/MaskRotation.svg.zip)

Please have a look at example. I use my file in `GrayscaleTigerViewController`

[PocketSVG-master.zip](https://github.com/pocketsvg/PocketSVG/files/3538275/PocketSVG-master.zip)

**Comment by arielelkin** [comment]
There is a rotation, but your transform being 180 degrees so it may not be immediately apparent 😉
