### ISSUE TITLE
can not parse  <defs> in the SVG file then show only black and white

### ISSUE THREAD

**Issue by Lisajoy512** [pocketsvg/PocketSVG#171]
Hi,I found PocketSVG cannot parse the <defs> in the SVG file,as below:
<defs><style>.cls-1{fill:#d31e97;}.cls-2{fill:#1dd640;}.cls-3{fill:#1a79d8;}.cls-4{fill:#e7ff00;}.cls-5{fill:#f70000;}.cls-6{fill:#2300f4;}</style></defs>

It can only show black and white

**Comment by fjolnir** [comment]
`<style>` tags aren't supported currently
