### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by heckj** [pocketsvg/PocketSVG#177]
More a request, or possibly a question - has there been any consideration to making this into a swift package that could be imported and used by SwiftPM within Xcode 11+?

**Comment by arielelkin** [comment]
No, but now yes.

**Comment by arielelkin** [comment]
quick update: i started work on this, and it's 99% done: https://github.com/pocketsvg/PocketSVG/pull/178

Unfortunately we need to wait for SPM to provide support for resources (as PocketSVG relies on SVGColors.plist, and its tests rely on SVG files).
