### ISSUE TITLE
How to convert UIBezierpath to SVG?

### ISSUE THREAD

**Issue by firattamur** [pocketsvg/PocketSVG#194]
Hello,

I am trying to create a coloring app. I can read svg image and fill their backgrounds. I want to save my UIBezier paths as svg after coloring process is done. I saw the function `SVGStringFromCGPaths` path I could not figure out how to set AttributeSet of svg? A short explanation or a small examples would be great.

Thanks,

**Comment by fjolnir** [comment]
You'll have to iterate over the path array(and change its type to `[SVGBezierPath]`), then for each of the paths, use `pathBySettingSVGAttributes:` with the svg attributes you want to change. It'll return a new path reflecting the changes.

something like
```swift
let attributeSet = SVGMutableAttributeSet()
let paths = shapeLayers.map { layer in 
    let path = paths[shapeLayerIndices[layer]]
    let newPath = path.pathBySettingSVGAttributes(["fill": layer.backgroundColor])
    attributeSet.set(attributes: path.svgAttributes, forPath: newPath.CGPath)
    return newPath.CGPath
}

let svgString = SVGStringFromCGPaths(updatedPaths, attributeSet)
```
I haven't actually compiled the above, but the general idea should work.

**Comment by firattamur** [comment]
Thanks a lot! I will try it and share the results.

**Comment by firattamur** [comment]
Hello,

I have tried your code. I got the error in below. I tried to give color parameter as UIColor and CgColor but neither of them worked. 

![Screen Shot 2021-10-13 at 7 43 07 PM](https://user-images.githubusercontent.com/34976672/137177360-03757468-ff3f-4f39-aa62-1767ca32419d.png)
![Screen Shot 2021-10-13 at 7 42 50 PM](https://user-images.githubusercontent.com/34976672/137177364-48e8c8e7-067d-4e2c-909a-bcd1b5855600.png)

Thanks,

**Comment by CodeForRabbit** [comment]
> ```swift
> SVGStringFromCGPaths
> ` for(NSString *key in pathAttrs) {
            if(![pathAttrs[key] isKindOfClass:[NSString class]]) { // Color
                [svg appendFormat:@" %@=\"%@\"", key, hexTriplet((__bridge CGColorRef)pathAttrs[key]).string()];
                if (CFGetTypeID((__bridge CFTypeRef)(pathAttrs[key])) == CGColorGetTypeID()) {
                    float const alpha = CGColorGetAlpha((__bridge CGColorRef)pathAttrs[key]);
                    if(alpha < 1.0)
                        [svg appendFormat:@" %@-opacity=\"%.2g\"", key, alpha];
                }
               
            } else
                [svg appendFormat:@" %@=\"%@\"", key, pathAttrs[key]];
        }

**Comment by fjolnir** [comment]
@CodeForRabbit It'd be great if you could make a PR with that
