### ISSUE TITLE
convert UIBezierpath to SVG

### ISSUE THREAD

**Issue by YJLgithub** [pocketsvg/PocketSVG#198]
### Steps to reproduce the issue

   AFBrushBoard毛笔画板框架画完的图片怎么转SVG？

Please include all relevant **code**, including **all** `PocketSVG` method calls made.

### Has my issue been reported? 

My issue has been reported in the following [closed issues](https://github.com/pocketsvg/PocketSVG/issues?q=is%3Aissue+is%3Aclosed):

### Specifications

  - PocketSVG Version: 
  - Xcode Version:
  - iOS/macOS Version:

**Comment by arielelkin** [comment]
你好 @YJLgithub 
对不起，我不会说中文
你能用英文写下你的问题吗

**Comment by fjolnir** [comment]
if you can get it to pass you a UIBezierPath, then you can use `SVGStringFromCGPaths`.

**Comment by YJLgithub** [comment]
> if you can get it to pass you a UIBezierPath, then you can use `SVGStringFromCGPaths`.

ok, I try it

**Comment by YJLgithub** [comment]
> if you can get it to pass you a UIBezierPath, then you can use `SVGStringFromCGPaths`.

I tried it, and it worked, but the turning point would break, what was the reason?

**Comment by YJLgithub** [comment]
> use `SVGStringFromCGPath`



> 你好 @YJLgithub 对不起，我不会说中文 你能用英文写下你的问题吗

i use SVGStringFromCGPaths. I tried it, and it worked, but the turning point would break, what was the reason?

**Comment by YJLgithub** [comment]
> > use `SVGStringFromCGPath`
> 
> > 你好 @YJLgithub 对不起，我不会说中文 你能用英文写下你的问题吗
> 
> i use SVGStringFromCGPaths. I tried it, and it worked, but the turning point would break, what was the reason?



> if you can get it to pass you a UIBezierPath, then you can use `SVGStringFromCGPaths`.



> 
<img width="1386" alt="WechatIMG54" src="https://user-images.githubusercontent.com/19282048/146314656-3377cc75-3384-44f5-8ad7-831949504847.png">

Truncated SVG story image

**Comment by YJLgithub** [comment]
> > use `SVGStringFromCGPath`
> 
> > 你好 @YJLgithub 对不起，我不会说中文 你能用英文写下你的问题吗
> 
> i use SVGStringFromCGPaths. I tried it, and it worked, but the turning point would break, what was the reason?



> if you can get it to pass you a UIBezierPath, then you can use `SVGStringFromCGPaths`.



> 
<img width="1386" alt="WechatIMG54" src="https://user-images.githubusercontent.com/19282048/146314656-3377cc75-3384-44f5-8ad7-831949504847.png">

Truncated SVG story image

**Comment by fjolnir** [comment]
That looks like a pretty strange path it’s giving you. It’s a bunch of segments perpendicular to the curve.
It’s not in the scope of PocketSVG to resolve.
