### ISSUE TITLE
The path I've drawn is truncated

### ISSUE THREAD

**Issue by YJLgithub** [pocketsvg/PocketSVG#199]
### Steps to reproduce the issue

  1. convert SVGBezierPath to SVG

  2 . i use SVGStringFromCGPaths. I tried it, and it worked, but the turning point would break, what was the reason?

  3.  As shown in the figure below

   
<img width="1386" alt="WechatIMG54" src="https://user-images.githubusercontent.com/19282048/146315545-b8a7d30d-f8b6-4c40-a38f-89888dd3e55e.png">

  

Please include all relevant **code**, including **all** `PocketSVG` method calls made.

### Has my issue been reported? 

My issue has been reported in the following [closed issues](https://github.com/pocketsvg/PocketSVG/issues?q=is%3Aissue+is%3Aclosed):

### Specifications

  - PocketSVG Version: 
  - Xcode Version:
  - iOS/macOS Version:

**Comment by fjolnir** [comment]
I replied in the original ticket
