### ISSUE TITLE
Carthage: Dependency "PocketSVG" has no shared framework schemes

### ISSUE THREAD

**Issue by pawelgil** [pocketsvg/PocketSVG#200]
### Steps to reproduce the issue

Cannot install PocketSVG with Carthage (`carthage update`) with following Cartfile:
```
github "pocketsvg/PocketSVG" ~> 2.4
```

Output:
```
*** Cloning PocketSVG
*** Checking out PocketSVG at "2.7.2"
*** xcodebuild output can be found in /var/folders/xq/n7_r0wzd0vsdr_zq1gphzvjh0000gn/T/carthage-xcodebuild.3q184x.log
*** Skipped building PocketSVG due to the error:
Dependency "PocketSVG" has no shared framework schemes
```

### Has my issue been reported? 

My issue has been reported in the following [closed issues](https://github.com/pocketsvg/PocketSVG/issues/190):

### Specifications

  - PocketSVG Version: 2.7.2
  - Xcode Version: 13.2.1
  - iOS/macOS Version: Big Sur

**Comment by arielelkin** [comment]
@pawelgil this should be fixed in PocketSVG 2.7.2 

please try again ([instructions on how to update Cartfile](https://github.com/pocketsvg/PocketSVG/blob/master/README.md#carthage)) and reopen this issue if you run into problems.
