### ISSUE TITLE
No spaces between Arc's large-arc-flag, sweep-flag and x is not handled

### ISSUE THREAD

**Issue by stevekuo** [pocketsvg/PocketSVG#204]
It appears that removing the spaces between Arc's `large-arc-flag`, `sweep-flag` and `x` is permitted by popular SVG renders. I can't find this in the SVG spec but web browsers and [this SVG path editor](https://yqnn.github.io/svg-path-editor/) permits it.

Example: `M 0 0 a 2 1 0 0 0 6 0` is

x-axis-rotation=0
large-arc-flag=0
sweep-flag=0
dx=6, dy=0

which can be shorted as `M 0 0 a 2 1 0 006 0`. PocketSVG [complains](https://github.com/pocketsvg/PocketSVG/blob/09c9dc258a4d8d49b4cd9edbed506f550d9a85b7/Sources/SVGEngine.mm#L780) that `a` does not have 7 elements

Other combinations are also permitted but not handled by PocketSVG, e.g.

`M 0 0 a 2 1 0 00 6 0` is the same as `M 0 0 a 2 1 0 0 0 6 0`

**Comment by fjolnir** [comment]
Yeah, seems like this should be handled. 
The grammar is here: https://www.w3.org/TR/SVG2/paths.html#PathDataBNF

**Comment by arielelkin** [comment]
fixed via https://github.com/pocketsvg/PocketSVG/pull/205
