### ISSUE TITLE
Syntax for pathsFromSVG when inputing the svg as a sting instead of a file

### ISSUE THREAD

**Issue by TyTodd** [pocketsvg/PocketSVG#216]
Hello I was wondering what the syntax was for getting a path from an svg when the input is a string representation of the svg and not the pathname of a file that stores it.

**Comment by arielelkin** [comment]
Take a look at [`CGPathFromSVGPathString`](https://github.com/pocketsvg/PocketSVG/blob/master/Sources/include/SVGEngine.h#L39)
