### ISSUE TITLE
App crash when returned CGPath is released, CGPath ownership

### ISSUE THREAD

**Issue by sosale151** [pocketsvg/PocketSVG#37]
Who owns the returned CGPath from my SVG? I assumed I was under ownership. However, when I use that CGPath inside drawRect, there is an app crash when the view controller is popped from the navigation stack. 

Note, the actual release statement I call successfully releases the object. The crash occurs after the view controller is popped from the navigation stack. This does not occur if I remove my own release statement. I'm guessing it's released again somewhere, hence the question about ownership.

**Comment by arielelkin** [comment]
PocketSVG has been updated to v2.0.0! This issue should not be relevant anymore now, but let me know if you still notice it. Happy coding!
