### ISSUE TITLE
Getting path is slow

### ISSUE THREAD

**Issue by aykutt** [pocketsvg/PocketSVG#43]
Hi,

I am using `pathFromSVGFileNamed` and it takes 50-90 ms for a svg to get path. I am working with multiple svg images so it became really slow. There is something wrong or it is normal to take a long time to render?

Thanks

**Comment by arielelkin** [comment]
Performance depends on the device hardware and on the complexity of the path.. If you notice some lag when generating `CGPaths` I'd recommend you execute it on a background queue.
