### ISSUE TITLE
Multiple path

### ISSUE THREAD

**Issue by Rufy86** [pocketsvg/PocketSVG#44]
Hi everyone,

i know that actually this class support only one path (last path, precisely), but i need to animate the KanjiVG's files that are SVG file representing order stroke kanji (japanese ideograms) and this SVG has more one path. How can I get the array containing the paths?

**Comment by arielelkin** [comment]
One way would be to parse the SVG file yourself, get the paths and pass it to `pathFromDAttribute`.

**Comment by arielelkin** [comment]
PocketSVG has been updated to v2.0.0! Multiple paths are supported now. Happy coding!
