### ISSUE TITLE
Not able to get the Cicrle path

### ISSUE THREAD

**Issue by tikamchandrakar18** [pocketsvg/PocketSVG#46]
I have test the below image , I am not able to get the correct path. Which tool we can use to create svg image which support the circle or curve path

Please let us know which tool we would be use to create SVG image.
[Cicle.zip] (https://github.com/arielelkin/PocketSVG/files/267555/Cicle.zip)

**Comment by arielelkin** [comment]
Hi @novumcoder 

PocketSVG has been updated to v2.0.0! Multiple paths should be supported now. Happy coding!
