### ISSUE TITLE
Not displaying correct shape?

### ISSUE THREAD

**Issue by jwoertink** [pocketsvg/PocketSVG#49]
I downloaded a [play icon](https://www.iconfinder.com/icons/352072/arrow_play_icon#size=128) svg, but when I render it, it shows up as a square.

Here's the SVG markup
```xml
<?xml version="1.0" ?>
<svg height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg">
  <path d="M-838-2232H562v3600H-838z" fill="none"/>
  <path d="M16 10v28l22-14z"/>
  <path d="M0 0h48v48H0z" fill="none"/>
</svg>
```

Here's the swift code

```swift
let playIconPath = PocketSVG.pathFromSVGFileNamed("play").takeUnretainedValue()
let iconShapeLayer = CAShapeLayer()
iconShapeLayer.path = playIconPath
iconShapeLayer.strokeColor = UIColor.whiteColor().CGColor
iconShapeLayer.lineWidth = 3
iconShapeLayer.fillColor = UIColor.whiteColor().CGColor
iconShapeLayer.position.x = CGRectGetMidX(self.frame)
iconShapeLayer.position.y = CGRectGetMidY(self.frame)
self.view!.layer.addSublayer(iconShapeLayer)
```
Here's a screenshot of what I see...

![screen shot 2016-06-16 at 9 48 05 am](https://cloud.githubusercontent.com/assets/2391/16125213/7c5076ea-33a7-11e6-989c-8397b104e7ac.png)

**Comment by arielelkin** [comment]
your SVG markup has three different paths, PocketSVG v1 only supports the rendering of one path. 

try removing the <path d> tags you don't need from your SVG file..

Support for multiple paths is coming in v2.

**Comment by arielelkin** [comment]
Hi @novumcoder 

PocketSVG has been updated to v2.0.0! Multiple paths are supported now. Happy coding!
