### ISSUE TITLE
Shapes loaded seem to be rotated by 180°

### ISSUE THREAD

**Issue by novumcoder** [pocketsvg/PocketSVG#53]
I was wondering why my shapes look different from what i saw in the SVG loaded in my browser.
It looks like PocketSVG is loading the path somehow rotated.
In order to get it printed as seen on the browser i need to tranform the shape by 180°.
Did i miss something here or is this is a bug?

My code is very simple:

```
let svg = PocketSVG.pathFromSVGFileNamed("example").takeUnretainedValue()
let sh = SKShapeNode( path: svg, centered: true)
self.addChild(sh)
```

The code above works fine, but the shape is printed in a 180° rotated state.

**Comment by arielelkin** [comment]
is this iOS or macOS?

**Comment by novumcoder** [comment]
iOS

**Comment by novumcoder** [comment]
ok i tried to rotate manually, actually it is not rotated by PocketSVG it is mirrored/reflected.

**Comment by novumcoder** [comment]
why you closed this issue?

**Comment by arielelkin** [comment]
Because given your last comment I thought that you had resolved the issue.. Is PocketSVG causing the issue?

**Comment by novumcoder** [comment]
yes it is.

i thought PocketSVG is rotating or loading it in a wrong angle, but actually it is loaded in a mirrored manner. So fixing by manually rotating (with CGAffineTransform) didn't help.

Can you check loading some this SVG (its a simple clock) and check if on SKScene it is rendered the same way you can see it loaded in your browser or some preview?
[clock.svg.zip](https://github.com/arielelkin/PocketSVG/files/448379/clock.svg.zip)

 and verifying the rendered node is still pointing to right. In my case the arro

**Comment by arielelkin** [comment]
Hi @novumcoder 

PocketSVG has been updated to v2.0.0! Please let me know if your issue is still happening on this new version.
