### ISSUE TITLE
Not loading file

### ISSUE THREAD

**Issue by rtnm** [pocketsvg/PocketSVG#58]
Hello.
Not loading file king.svg (
[king.zip](https://github.com/pocketsvg/PocketSVG/files/515275/king.zip))
What is the problem?
Thanks!

**Comment by arielelkin** [comment]
looks like it's not a valid SVG v1.1 file.

Run it through this:
https://validator.w3.org/check

And select SVG 1.1 as the doctype.

@fjolnir any thoughts?

**Comment by fjolnir** [comment]
Ooff... that's one hideous SVG file. But it is probably valid, just fails as SVG 1.1 because it has inkscape extensions.

I'll try to find what is broken, but I can't promise anything.

**Comment by grifas** [comment]
Same problem :/

**Comment by fjolnir** [comment]
With the exact same file?

**Comment by grifas** [comment]
I resolved my issue with:

```let url = Bundle.main.url(forResource: "name_of_my_image", withExtension: "svg")!

and after

```for path in SVGBezierPath.pathsFromSVG(at: url) {```

**Comment by arielelkin** [comment]
@rtnm are you still noticing the issue?
