### ISSUE TITLE
Unable to build the version 2.0.0. Its giving linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by vrkkarthi** [pocketsvg/PocketSVG#62]
Undefined symbols for architecture arm64:
  "operator new(unsigned long)", referenced from:
      std::__1::__split_buffer<float, std::__1::allocator<float>&>::__split_buffer(unsigned long, unsigned long, std::__1::allocator<float>&) in libPocketSVG.a(SVGEngine.o)
  "std::__1::__vector_base_common<true>::__throw_length_error() const", referenced from:
      void std::__1::vector<float, std::__1::allocator<float> >::__push_back_slow_path<float const&>(float const&&&) in libPocketSVG.a(SVGEngine.o)
  "___cxa_begin_catch", referenced from:
      ___clang_call_terminate in libPocketSVG.a(SVGEngine.o)
  "operator delete(void_)", referenced from:
      std::__1::__vector_base<float, std::__1::allocator<float> >::~__vector_base() in libPocketSVG.a(SVGEngine.o)
      std::__1::__split_buffer<float, std::__1::allocator<float>&>::~__split_buffer() in libPocketSVG.a(SVGEngine.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libPocketSVG.a(SVGEngine.o)
  "___gxx_personality_v0", referenced from:
      svgParser::svgParser(NSString_) in libPocketSVG.a(SVGEngine.o)
      svgParser::svgParser(NSString_) in libPocketSVG.a(SVGEngine.o)
      svgParser::parse(NSMapTable_ __autoreleasing_) in libPocketSVG.a(SVGEngine.o)
      svgParser::readPathTag() in libPocketSVG.a(SVGEngine.o)
      svgParser::readPolygonTag() in libPocketSVG.a(SVGEngine.o)
      svgParser::readRectTag() in libPocketSVG.a(SVGEngine.o)
      svgParser::pushGroup(NSDictionary_) in libPocketSVG.a(SVGEngine.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Note:- When adding s.library    = 'xml2', **'stdc++'** to the podspec the linker error get resolved.

**Comment by arielelkin** [comment]
what version of Xcode are you using?

Do you get this error if you create a new project and add `pod PocketSVG` to it?

**Comment by sean-howard** [comment]
I'm having this same issue trying to import version 2.0.0 via Cocoapods into a fresh Objective-C project in Xcode 8.2.1. Is there a way to resolve this? @arielelkin @vrkkarthi?

**Comment by arielelkin** [comment]
@vrkkarthi thanks for the tip, v2.1.1.1 fixes this now

@sean-howard
