### ISSUE TITLE
How can I use pathFromDAttribute in V2?

### ISSUE THREAD

**Issue by bgdavidx** [pocketsvg/PocketSVG#64]
Hey there, we had an app that was using pathFromDAttribute in PocketSVG v1. We tried to upgrade the Pod to v2 and noticed this function is missing. How can we achieve this functionality in V2?

**Comment by arielelkin** [comment]
Hi @bgdavidx 

Sorry for the delay!

You can use the `pathsFromSVGNamed` method from `SVGBezierPath`.

See the example in the docs:
https://github.com/pocketsvg/PocketSVG#usage

**Comment by bgdavidx** [comment]
@arielelkin , I appreciate the response. This function doesn't create a `CGPath` from a `NSString` describing the path (like this for example: `M506.295 538.97 506.295 474.084 593.338 474.084 593.338 538.97 506.295 538.97`). Is there a function that does this?

**Comment by arielelkin** [comment]
Ah, I see. 

Then you want to look at the `CGPathsFromSVGString` method in [`SVGEngine`](https://github.com/pocketsvg/PocketSVG/blob/master/SVGEngine.h).

**Comment by bgdavidx** [comment]
@arielelkin This function doesn't seem to work either, because it expects an XML string as input. For instance, `<path d="M506.295 538.97 506.295 474.084 593.338 474.084 593.338 538.97 506.295 538.97" />`, not just the input `M506.295 538.97 506.295 474.084 593.338 474.084 593.338 538.97 506.295 538.97`. Is there a way to parse only the D attribute?

**Comment by arielelkin** [comment]
ah, nope, sorry, we deprecated that because we prefer deal with SVG data that conforms to the [Spec](https://www.w3.org/TR/SVG/), i.e. in XML.
