### ISSUE TITLE
Implement quad curve support

### ISSUE THREAD

**Issue by novumcoder** [pocketsvg/PocketSVG#65]
It is loading successfully but not showing the shield icon as expected, it simply looks broken.

What is wrong with this file? It is valid checked by w3c (svg 1.1).

[shield.svg.zip](https://github.com/pocketsvg/PocketSVG/files/578767/shield.svg.zip)

**Comment by fjolnir** [comment]
It's because quad curves are not supported yet.

The error message `*** Error: Cannot process command : 'q'` refers to that.
