### ISSUE TITLE
SVG circle element does not work

### ISSUE THREAD

**Issue by pbmorton** [pocketsvg/PocketSVG#66]
Release 2.0.0 of PocketSVG displays all my SVG files except it stubbornly refuses to display circle elements. The following is contents from a simple SVG file that uses a circle element. It works on Inkscape, Internet Explorer, Irfanview and other applications. But PocketSVG will not display the circle.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xml:space="preserve"
   style="enable-background:new 0 0 950.4 950.4;"
   viewBox="0 0 950.4 950.4"
   height="950.4px"
   width="950.4px"
   y="0px"
   x="0px"
   id="Capa_1"
   version="1.1"><metadata
     id="metadata49"><rdf:RDF><cc:Work
         rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" /><dc:title></dc:title></cc:Work></rdf:RDF></metadata><defs
     id="defs47" /><g
     id="g3"><g
       id="g5"
       style="fill:#000080"><circle
         id="circle11"
         r="194"
         cy="467.43304"
         cx="492.00677"
         style="fill:#000080" /></g></g><g
     id="g15" /><g
     id="g17" /><g
     id="g19" /><g
     id="g21" /><g
     id="g23" /><g
     id="g25" /><g
     id="g27" /><g
     id="g29" /><g
     id="g31" /><g
     id="g33" /><g
     id="g35" /><g
     id="g37" /><g
     id="g39" /><g
     id="g41" /><g
     id="g43" /></svg>

**Comment by pbmorton** [comment]
To follow up on my previous comment, I integrated the changes in https://github.com/samus/PocketSVG/ supporting circle elements (pull request https://github.com/pocketsvg/PocketSVG/pull/59). These changes successfully support circles for the small number of SVG files I've tested. Aside, thanks for your efforts producing PocketSVG!

**Comment by arielelkin** [comment]
Thanks for letting us know @pbmorton 

We'll work on getting that PR merged. Sorry for the delay.

**Comment by fjolnir** [comment]
Just merged the <circle> changes. Should work now.
