### ISSUE TITLE
How to show svg image in right position?

### ISSUE THREAD

**Issue by misteral** [pocketsvg/PocketSVG#69]
Sorry for nub question, I am start with swift and stuck with a problem in my app, I can't show the svg image in my app in this position.
![Alt text](https://monosnap.com/file/rCGPQWyvp5fa6bVYuy5JIWTzLPwK2Y.png) 

Thanks.

**Comment by Shmaff** [comment]
It appears that you haven't added any layout constraints yet. I can tell because there are no blue markings in your image from Interface Builder. It's probably rendering offscreen due or the image name isn't correct.

**Comment by misteral** [comment]
Thank @Shmaff try to do that.

**Comment by arielelkin** [comment]
closing for now, let us know @Shmaff's suggestion does not fix your issue.
