### ISSUE TITLE
A few missing SVG commands

### ISSUE THREAD

**Issue by ABCOM2000** [pocketsvg/PocketSVG#7]
Can you add support for the following SVG commands?

Q = quadratic Bézier curve
T = smooth quadratic Bézier curveto
A = elliptical Arc

A simple path taken from SVG is given below for testing

d="M318.357,35.882 Q313.38,28.763 308.97,26.716 C308.088,26.306 307.206,25.928 306.292,25.582 308.088,30.527 309.096,35.756 309.348,41.332 309.411,42.497 309.442,43.663 309.411,44.828 309.348,53.018 309.19,61.208 308.938,69.398 308.718,77.305 307.111,84.991 304.15,92.52 301.095,100.269 296.275,105.939 289.691,109.561 287.455,110.79 285.124,111.672 282.635,112.239 L282.509,112.365 C283.738,113.94 285.187,115.263 286.856,116.334 290.479,118.57 294.448,118.948 298.763,117.468 303.079,115.987 306.481,112.365 308.938,106.6 311.332,100.962 313.38,95.103 315.112,89.023 316.782,83.196 317.884,77.116 318.451,70.847 318.924,65.303 319.27,59.728 319.491,54.089 319.617,50.152 319.459,45.899 319.018,41.332 318.861,39.694 318.64,38.024 318.42,36.323 318.388,36.166 318.388,36.04 318.357,35.882z"

Thanks!

**Comment by eonist** [comment]
MY SVGLib has support for these commands: https://github.com/eonist/swift-utils#svglib

Feel free to copy the code and add to this project. 

Its swift.

**Comment by arielelkin** [comment]
PocketSVG has been updated to v2.0.0! Multiple paths are supported now. Happy coding!

**Comment by eonist** [comment]
So Arc is supported now? would love to see how you did this. My Arc implementation works but, feels over-engineered.

**Comment by arielelkin** [comment]
actually, elliptical arcs aren't supported yet.

**Comment by arielelkin** [comment]
@eonist I saw what you did with SVGLib, love it. Would you like to integrate your arc implementation into PocketSVG? We're looking for contributors!

**Comment by eonist** [comment]
Ill be happy to implement the Arc command. But my objc is kind of rusty. Ping me once you guys go swift :D

**Comment by arielelkin** [comment]
at the moment we don't have plans to rewrite the engine in Swift. Historical reasons. 

But if you can write Swift you can definitely write ObjC, and I'd be happy to give you a hand. What do you say?

**Comment by eonist** [comment]
To be honist I can convert objc to sqift but not the other way around. After a year with only swift ive fogotten most of the objc language. But I can offer to outline how to implement the arc command in a wiki.
