### ISSUE TITLE
About supporting iOS 8

### ISSUE THREAD

**Issue by lancy** [pocketsvg/PocketSVG#70]
I would like to use PocketSVG in my project, however I notice that in the .podspec file, the iOS deployment target has been set to iOS 9.

Is there any reason that make PocketSVG drop support for iOS 8? 
If I fork it and change the deployment target to iOS 8, what problem will I facing?

Thx

**Comment by arielelkin** [comment]
The deployment target there indicates what's the _minimum_ version required. So if it runs on iOS 8 it will run on iOS 9.

**Comment by Shmaff** [comment]
I suspect @lancy is trying to ask if this library will work in versions of iOS prior to iOS 9. If not, what code won't work if they try to build targetting an earlier OS?

**Comment by arielelkin** [comment]
Woops sorry, I misread @lancy's question. thanks @Shmaff.

Yes, it should work with iOS 8 and 7. Let us know if you run into any issues.

**Comment by nicolasmuller** [comment]
Hello @arielelkin, i'm using PocketSVG for my projects (iOS 8 compliant) for a while.

There's no problems to change the deployment target to iOS 8, can you change it ?

**Comment by fjolnir** [comment]
The default project deployment target is already set to 8.1. If the podspec is set to 9, that's a bug.
