### ISSUE TITLE
SVG file not rendering Ellipses

### ISSUE THREAD

**Issue by karimfikani** [pocketsvg/PocketSVG#72]
I'm rendering the following svg file (compressed into a zip file because github doesn't allow uploading svg files)
[firetruck.svg.zip](https://github.com/pocketsvg/PocketSVG/files/623718/firetruck.svg.zip)

and what I get is the following

![simulator screen shot nov 30 2016 9 06 42 pm](https://cloud.githubusercontent.com/assets/2486075/20782516/5477d9ba-b741-11e6-8dfe-80b4838aa7ed.png)

It seems that the library doesn't support the ellipse shape, am I correct?

**Comment by arielelkin** [comment]
Correct, [we're working on that](https://github.com/pocketsvg/PocketSVG/pull/59).

**Comment by fjolnir** [comment]
Just merged support, renders like this now:

![render](http://d.asgeirsson.is/biXi.png)
