### ISSUE TITLE
typo in SVGLayer.m 

### ISSUE THREAD

**Issue by dshahnaz** [pocketsvg/PocketSVG#73]
File  SVGLayer.m .
Line 126 :
"- (void)setSvgName:(NSString *)svgName {
....
    NSPredicate * const pred = [NSPredicate predicateWithFormat:@"lastPathComponent LIKE[c] %@",    [**aFileName** stringByAppendingPathExtension:@"svg"]];
"

I suppose it should be :
"- (void)setSvgName:(NSString *)svgName {
....
    NSPredicate * const pred = [NSPredicate predicateWithFormat:@"lastPathComponent LIKE[c] %@",    [**svgName** stringByAppendingPathExtension:@"svg"]];
"
error : "Use of undeclared identifier 'aFileName'"

I have installed PocketSVG pod latest version.
Somehow this issue not appear in build time.I got it on "Report navigation" interface builder section when  tried use some custom IBDesignable view(Not from pod).
In the result in Interface builder IBDesignable views always failed.

**Comment by arielelkin** [comment]
Hi @dshahnaz. In order for us to help you out, could you please upload an Xcode project that reproduces your problem?

**Comment by fjolnir** [comment]
Thanks a lot!

(it only failed to compile when using in interface builder)
