### ISSUE TITLE
Doesnt work and incorrect bezierPath attributes when in .svg file was used classes

### ISSUE THREAD

**Issue by Sroik** [pocketsvg/PocketSVG#74]
![226614875_16810921154685593219](https://cloud.githubusercontent.com/assets/7701363/21056154/7b87b7ae-be45-11e6-9740-e2898409e4f0.jpg)
<img width="385" alt="screen shot 2016-12-09 at 7 26 17 pm" src="https://cloud.githubusercontent.com/assets/7701363/21056155/7b883eb8-be45-11e6-914a-a52b31c8f436.png">

**Comment by arielelkin** [comment]
Hi @Sroik ! Could you please paste the full code of the SVG file?

**Comment by Sroik** [comment]
I have resolved this problem here https://github.com/jmenter/JAMSVGImage/pull/40

Here it is:
<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 300 300" style="enable-background:new 0 0 300 300;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#27AAE1;stroke:#ED1C24;stroke-width:10;stroke-miterlimit:10;}
</style>
<polygon class="st0" points="210,218.7 124.6,223 78.2,151.3 117.1,75.2 202.5,70.9 248.9,142.6 "/>
</svg>

**Comment by fjolnir** [comment]
Classes are not supported, nor are <style> tags. I'm not sure if it can be done without bloating things more than I'd like.

(This framework does not aim to be a fully featured SVG renderer, but a fast one. SVGKit is much better in that regard.)
