### ISSUE TITLE
KanjiVG loop animations

### ISSUE THREAD

**Issue by Rufy86** [pocketsvg/PocketSVG#75]
Following the instructions I can get an array of cashapelayer, add an animation that show how to draw the stroke to every layer, and add the layer to view. When launch the app I can see the animation, but only one time. How can I loop the  entire animation? The animation show how draw every stroke of kanji and it do it stroke by stroke. But when finish I want that everything is cleaned and the animation restarts. How can I do it?

**Comment by arielelkin** [comment]
Hi @Rufy86! In order to help you out, could you please provide use with code we can paste into an Xcode Playground to reproduce your issue?

**Comment by arielelkin** [comment]
If you can't import PocketSVG into an Xcode playground, you can also upload an Xcode project that reproduces the error.

**Comment by fjolnir** [comment]
CAAnimation has a `repeatCount` property, that should be helpful. But this ticket is not really related to PocketSVG, so I'm closing it.

But feel free to ask follow-up questions and I'll answer them if I can.
