### ISSUE TITLE
How to use it in Xcode 8/Swift 3 properly? I got just black color shape.

### ISSUE THREAD

**Issue by odvan** [pocketsvg/PocketSVG#78]
What I'm doing wrong?

In UIWebView the same file is colored, also in SVGKit

![svgpocket](https://cloud.githubusercontent.com/assets/23110283/23306929/9d40e2aa-fab6-11e6-9786-d370f755537a.png)

**Comment by odvan** [comment]
Solved with using storyboard: dragginng UIVIew and then changing class to SVGImageView. Just like in demo. May add probably didn't do it properly first time because I didn't add constraints, neither CGRect size.

Also some SVG files can't be rendered. The same issue as #68

**Comment by fjolnir** [comment]
SVGLayer/View have properties to override the fill & stroke colors, maybe they were not nil.
