### ISSUE TITLE
Please consider Carthage support

### ISSUE THREAD

**Issue by mrubin** [pocketsvg/PocketSVG#79]
Could you please consider adding Carthage support?

Thank you

**Comment by arielelkin** [comment]
done. 

add the following to your cart file: 

`github "pocketsvg/PocketSVG"`

Then run `carthage update`.

Please let me know if it works!

**Comment by arielelkin** [comment]
closed via https://github.com/pocketsvg/PocketSVG/commit/c629b5261e4233a0917360c16836605abfad5113
