### ISSUE TITLE
After successful pod update, SVGBezierPath unknown

### ISSUE THREAD

**Issue by novumcoder** [pocketsvg/PocketSVG#80]
I added the pod PocketSVG into my Podfile, ran pod update which successfully added the pod data, then i restarted my project in xCode but still, i cannot use classes like SVGBezierPath. Tried import PocketSVG but that didn't work out. What am i doing wrong? Anything to set on the project?

**Comment by arielelkin** [comment]
Hi @novumcoder 

I need more details in order to help you out: 

* Are you opening the xcode project or the xcode workspace? 
* Are you trying to import the classes into a Swift or an ObjC file? 
* What specific error message are you seeing? 

Cheers

**Comment by novumcoder** [comment]
- opening it via xcode workspace as mentioned in the guideline
- it is a swift file iam trying to import to
- the error message is **Use of unresolved identifier SVGBezierPath** while im trying to call method pathsFromSVG. I tried either with import PocketSVG and without. Same problem.

**Comment by arielelkin** [comment]
can you post the code of the file where the error message happens?

**Comment by novumcoder** [comment]
```
 class func createFromSVG(_ name: String, size: CGSize) -> CGPath {
        let url = Bundle.main.url(forResource: name, withExtension: "svg")!
        let paths = SVGBezierPath.pathsFromSVG(at: url)
        let svg = UIBezierPath()
        for i in paths {
            let bez = UIBezierPath(cgPath: i.cgPath)
            svg.append(bez)
        }
        ...
```

**Comment by arielelkin** [comment]
looks like you're doing everything correctly in the code, so the problem must be elsewhere. if you're using cocoapods, and have indeed opened the workspace that cocoapods created, then you shouldn't have these errors.. 

in order for me to help you further, i need to be able to reproduce your issue. are you able to send me a sample xcode project that reproduces this error?

**Comment by novumcoder** [comment]
sorry, can't provide that, but i wonder if my Pods-Demo.debug.xcconfig is right, the frameworks path does not contain the PocketSVG stuff, is that right? I have also GoogleAdMob added.

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/FirebaseAnalytics/Frameworks" "${PODS_ROOT}/FirebaseCore/Frameworks" "${PODS_ROOT}/FirebaseInstanceID/Frameworks" "${PODS_ROOT}/Google-Mobile-Ads-SDK/Frameworks/frameworks"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) ${PODS_ROOT}/Firebase/Core/Sources $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Firebase" "${PODS_ROOT}/Headers/Public/FirebaseAnalytics" "${PODS_ROOT}/Headers/Public/FirebaseCore" "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK" "${PODS_ROOT}/Headers/Public/GoogleToolboxForMac" "${PODS_ROOT}/Headers/Public/PocketSVG"
LIBRARY_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac" "$PODS_CONFIGURATION_BUILD_DIR/PocketSVG"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Firebase" -isystem "${PODS_ROOT}/Headers/Public/FirebaseAnalytics" -isystem "${PODS_ROOT}/Headers/Public/FirebaseCore" -isystem "${PODS_ROOT}/Headers/Public/FirebaseInstanceID" -isystem "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK" -isystem "${PODS_ROOT}/Headers/Public/GoogleToolboxForMac" -isystem "${PODS_ROOT}/Headers/Public/PocketSVG"
OTHER_LDFLAGS = $(inherited) -ObjC -l"GoogleToolboxForMac" -l"PocketSVG" -l"c++" -l"sqlite3" -l"z" -framework "AVFoundation" -framework "AudioToolbox" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreVideo" -framework "FirebaseAnalytics" -framework "FirebaseCore" -framework "FirebaseInstanceID" -framework "GLKit" -framework "GoogleMobileAds" -framework "MediaPlayer" -framework "MessageUI" -framework "MobileCoreServices" -framework "OpenGLES" -framework "QuartzCore" -framework "StoreKit" -framework "SystemConfiguration" -weak_framework "AdSupport" -weak_framework "JavaScriptCore" -weak_framework "SafariServices" -weak_framework "WebKit"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by adamjsutcliffe** [comment]
I believe this could be you iOS deployment target! I had this same issue when using pods, i built a test project to use PocketSVG which had a deployment target of iOS 10 then after a successful spike ;) i went to integrate it into my main app which has a target of iOS 8. Whilst my spike project used version 2.2.1 the main project only used version 0.7 and if i forced a higher version in the podfile it complained `Specs satisfying the `PocketSVG (= 2.1.1)` dependency were found, but they required a higher minimum deployment target.` A work around I am using temporarily is to import the files from the test project into my main project, a bit cheeky but it works, if you cant change your deployment target that is ;) Hope this helps

**Comment by arielelkin** [comment]
thanks @adamjsutcliffe 

@novumcoder let us know if that helps?

**Comment by novumcoder** [comment]
sorry i think i didn't understand.

i have one project to which i now added PocketSVG into my Podfile.

I also created a blank project then added a new Podfile with this:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'PuckIt' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'PocketSVG'
end
```

Having my deployment target at 9.0. GoogleMobileAds stuff is working fine, but PocketSVG is still of undeclared type.

Could you give me a step-by-step description on how to add PocketSVG on a blank project, it very seems like i forgot something here.

**Comment by arielelkin** [comment]
@novumcoder 

Try to see if you can solve your issue by following the advice here: https://guides.cocoapods.org/using/troubleshooting.html

If that doesn't help, create a github repository and push that project there. let me know about it and i'll then make a pull request that shows you how to import it.

**Comment by novumcoder** [comment]
Ok just created a new blank project (as game with swift and spritekit) then used my Podfile. Still not working. I pushed this project into my github account.

https://github.com/novumcoder/podtest.git

Thanks for the help.

**Comment by arielelkin** [comment]
Hi @novumcoder, I was able to reproduce your issue. I'm working on a fix and will keep you posted.

**Comment by novumcoder** [comment]
Thanks a lot, waiting for your feedback.

**Comment by novumcoder** [comment]
Hi @arielelkin,

found anything?

**Comment by novumcoder** [comment]
For your info. This must be some problem with your pod setup.
I added one ObjC Bridging Header für PocketSVG importing all .h files and also added all .h and .mm files manually to Compile Sources on Build phases tab. Then it worked.
So you need to check why this is not done by the pod install.

**Comment by arielelkin** [comment]
also see https://github.com/pocketsvg/PocketSVG/issues/84#issuecomment-317864654

**Comment by novumcoder** [comment]
Nope, same problem. after changing podfile i executed "pod update" then opened the xworkspace file. typing SVGBe... it still doesn't list the SVG classes.

**Comment by arielelkin** [comment]
try running `pod install` instead.

if that doesn't work, please paste here the Podfile you're using.

**Comment by novumcoder** [comment]
Nope, but when trying to Clean and Build i now get this error:

`ld: warning: directory not found for option '-F/Users/Admin/TestApp/DerivedData/TestApp/Build/Products/Debug-iphonesimulator/PocketSVG'
ld: framework not found PocketSVG
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by arielelkin** [comment]
Sorry but I'm not able to reproduce your error:
https://github.com/arielelkin/PocketSVGTester

It looks like something might be very wrong within your xcode project settings. I advise you to move your source code files and the Podfile to a new xcode project.
