### ISSUE TITLE
Text in SVG does not render

### ISSUE THREAD

**Issue by pbmorton** [pocketsvg/PocketSVG#81]
I'm using version 2.2.0. My SVG files with "text" do not render. The attached point_2_yellow_opt.svg has "text" and does not render (this file was saved via Inkscape as optimised SVG). If I take this file and via Inkscape menu "Path" select "Object to Path" and save as optimised SVG I get the attached file point_2_yellow_as_path_opt.svg. This is almost correct - the text is rendered but the border to the yellow teardrop shape is too thick.

So two questions:
1. Can you please support text so that point_2_yellow_opt.svg is correctly drawn by PocketSVG?

2. Can you fix the rendering so the outer black border of point_2_yellow_as_path_opt.svg is the correct thickness?

Thanks!

PS. github refused to upload SVG files or a zip file, so I changed the suffix of the files from svg to txt to attach them here. Please just rename them to .svg to try them.

[point_2_yellow_opt.txt](https://github.com/pocketsvg/PocketSVG/files/806233/point_2_yellow_opt.txt)
[point_2_yellow_as_path_opt.txt](https://github.com/pocketsvg/PocketSVG/files/806234/point_2_yellow_as_path_opt.txt)

**Comment by fjolnir** [comment]
`<text> is not supported, and most likely will never be.

As for the border, maybe you have `scaleLineWidth` set to `YES`?

**Comment by pbmorton** [comment]
You said "As for the border, maybe you have scaleLineWidth set to YES?"

No. Here's my code. I have added a code line to explicitly set svgLayer.scaleLineWidth=false and the border is still wrong.

    func getMarkerImage(forName name: String, width w:Int, height h: Int) -> UIImage? {
        
        let url = MarkerSvgStore.cacheDirectory.appendingPathComponent("m_" + name + ".svg")
        let frame = CGRect(x: 0, y: 0, width: w, height: h)
        let svgLayer = SVGLayer(contentsOf: url)
        svgLayer.scaleLineWidth=false
        svgLayer.frame = frame
        
        return self.snapshotImage(for: svgLayer)
    }
    
    // Code from https://github.com/pocketsvg/PocketSVG/issues/71
    private func snapshotImage(for layer: CALayer) -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(layer.bounds.size, false, UIScreen.main.scale)
        guard let context = UIGraphicsGetCurrentContext() else { return nil }
        layer.render(in: context)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }

**Comment by fjolnir** [comment]
These all look roughly the same to me:

![borders](http://d.asgeirsson.is/Cmdc.png)

Am I missing something?

**Comment by pbmorton** [comment]
I see PocketSVG display this, with wider outer lines:
![capturesvg](https://cloud.githubusercontent.com/assets/8908488/23646963/5bebac18-034e-11e7-84c6-765e9bcf362e.JPG)

You obviously cannot reproduce the problem. I've been forced to stop using PocketSVG and move to another library that supports more SVG features so do not need this fixed. Thanks very much for you great support and good luck!

**Comment by fjolnir** [comment]
.. Your problem is that you *don't* have `scaleLineWidth` set to `YES`. The border is rendered correctly, but you're scaling down the path.

**Comment by kritikaperiwal12** [comment]
Is there any answer for "Text in SVG does not render"?

**Comment by fjolnir** [comment]
Yes, in the first and last comments.

**Comment by kritikaperiwal12** [comment]
> Yes, in the first and last comments.

<text> is not supported, and most likely will never be. Is there any solution for this. I am able to show my SVG image properly but the text is not showing in it. And I am using Pocket SVG framework.

**Comment by fjolnir** [comment]
There is no solution except to add support for it by yourself. But <text> support would probably be a major undertaking.

**Comment by fjolnir** [comment]
If you're making your own SVGs, a simple solution is to convert the text to path outlines.

**Comment by kritikaperiwal12** [comment]
Can I edit this in my SVG file by editing in text edit? Text tag in SVG 1.2 file is like:  <text transform="matrix(1 0 0 1 1032.8 310.4)" fill="#231F20" font-family="'Arial-BoldMT'" font-size="3.6px">T</text>

**Comment by fjolnir** [comment]
No, you'd want a tool like Sketch.

**Comment by kritikaperiwal12** [comment]
@fjolnir Can you tell me the procedure to convert the text to path outlines.

**Comment by fjolnir** [comment]
https://sketchapp.com/docs/text/convert-to-outlines/

**Comment by kritikaperiwal12** [comment]
I change some text layer to outline after open SVG file in Sketch. But during save that file, it is not allowing to save this using SVG extension. What should I do in this case? How to save this as SVG file after changes.   @fjolnir

**Comment by kritikaperiwal12** [comment]
Thanks for this much info. @fjolnir
