### ISSUE TITLE
Accessing original SVG size, possible incorrect bounds calculation?

### ISSUE THREAD

**Issue by SuperWomble** [pocketsvg/PocketSVG#82]
Firstly, let me say THANKYOU for this great project. The ability to handle multiple bezier paths is hugely appreciated!

**Preamble:**

I've come across an issue that has become apparent from my particular use-case. Rather than a `UIView` or `CALayer`, I'm in need of a generic drawing method that will draw the SVG's various paths into whatever `CGContext` is provided. (i.e. a method that supports both bitmap and vector/PDF output.)

To that end, I started writing such a method, using `SVGLayer's` `layoutSublayers` method as a starting point.

**Problem:**

I quickly came across a problem: there is a class of SVG images whose bounds is greater than the unioned parts. 

Example:  icons in a set. Each icon shares the same canvas size (128x128), but each individual icon has paths of different dimensions.) The background is transparent, and it is likely that no path touches one or more edges of the canvas.   The consistent canvas dimensions  here are important for the proper transformation and composition of the overall image, especially in relationship to other SVGs. 

Now, consider the following code, provided in `SVGLayer.m`:

```
- (CGSize)preferredFrameSize
{
    CGRect bounds = CGRectZero;
    for(SVGBezierPath *path in _untouchedPaths) {
        bounds = CGRectUnion(bounds, path.bounds);
    }
    return bounds.size;
}
```

This code returns a "frame" size that is the union of all path boundaries within the SVG. However, for a purpose such as the icon set describe above, this approach will not work, and will cause layout/drawing issues.

(Unless I'm missing something? Which is entirely possible.)

In such a situation, it would be preferable to access the native bounds of the SVG (i.e. the "width" and "height" tags), and use those for calculations.

**Proposed Solution**

I propose the addition of `nativeWidth` and `nativeHeight` accessors, and the use of those properties in a `nativeFrameSize(`) method, instead of unioning path boundaries.

Thank you.

**Comment by fjolnir** [comment]
SVGLayer trims the empty area around path by translating all paths to the origin of `bounds` so preferredFrameSize only takes into account the area actually occupied by points. See: https://github.com/pocketsvg/PocketSVG/blob/master/SVGLayer.m#L243 .

To render more faithfully, `size = { CGRectGetMaxX(path.bounds), CGRectGetMaxY(path.bounds) }` should give you a size big enough to draw a path as-is (if stroked, you need to take that into account too).

**Comment by SuperWomble** [comment]
Thanks for the help with this. I'm not entirely sure what you mean by the MaxX, MaxY approach. Wouldn't that still only give a result that is effectively a trimmed image, relative to the original SVG canvas size? Cheers.

**Comment by fjolnir** [comment]
No, the path "bounds" is more like a view's "frame", it includes the offset of the top-leftmost point

**Comment by fjolnir** [comment]
Was I missing the point, in that you wanted to also include the bottom right offset?

**Comment by saoudrizwan** [comment]
@SuperWomble Here's an implementation that I'm using (thanks @fjolnir) 
```swift
let svgLayer = SVGLayer(contentsOf: filePath)
svgLayer.fillColor = color.cgColor
        
var maxWidth: CGFloat = 0
var maxHeight: CGFloat = 0
for path in SVGBezierPath.pathsFromSVG(at: filePath) {
    let width = path.bounds.size.width
    if width > maxWidth {
        maxWidth = width
    }
    let height = path.bounds.size.height
    if height > maxHeight {
        maxHeight = height
    }
}
let frame = CGRect(x: 0, y: 0, width: maxWidth, height: maxHeight)
svgLayer.frame = frame
```

**Comment by fjolnir** [comment]
@saoudrizwan`svgLayer.preferredFrameSize` your code could be shortened by

**Comment by SuperWomble** [comment]
Sorry for the lack of feedback on this one... I got diverted by other work, wasn't able to continue with SVG work until now. The issue I had was really related to using the SVG overall canvas size as a reference point, and then drawing all paths relative to that reference. Many users will not need this, but it is vital for the current project. As a workaround, before loading the SVG with PocketSVG, I'm scraping the raw SVG file for the "width" and "height" values, using regex, caching the values, then doing all drawing relative to those values. Cheers.

**Comment by fjolnir** [comment]
Another hack would be an invisible path, that traces the canvas bounds, then you wouldn't need to read through the XML (Although the SVGs would need to be specially crafted)

**Comment by SuperWomble** [comment]
Hmm, that is a very good point. Damn, wish I'd thought of that earlier :)  Cheers.

**Comment by oiledCode** [comment]
@SuperWomble I would be interested in knowing more about your solution can you share some code?

**Comment by SuperWomble** [comment]
@oiledCode It's just some crufty regex that I threw together, with an eye to Sketch-produced SVGs. The regex could be more forgiving, but it works.

(There's a fair bit of code here, but the core idea is very short; just a few regex calls. But I rely on a lot of utility extensions for my work, so let me know if I missed one.)

Usage:

```
let xmlString = ...
 let size = xmlString.ss_NativeSVGDimensions()
```

```
extension String
{    
    /// The string should contain SVG XML data (preferably from Sketch).
    /// This method scrapes the string, returns the native dimensions of the SVG
    /// as described in the "width" and "height" properties in the XML.
    ///
    /// Returns nil if the native dimensions ("width", "height" couldn't be found.)

    func ss_NativeSVGDimensions() -> CGSize?
    {
        // Check for width and height independently, in case they're not in order.
        let widthPattern  = "<svg.*?width=\"([0-9]*)\"?"
        let heightPattern  = "<svg.*?height=\"([0-9]*)\"?"

        guard let width = SS_FirstCapture(forPattern: widthPattern,
                inString: self) else {
            print("WARNING: Couldn't find width in SVG string!")
            return nil
        }
        
        guard let height = SS_FirstCapture(forPattern: heightPattern,
                inString: self) else {
            print("WARNING: Couldn't find height in SVG string!")
            return nil
        }
        
        return CGSize(ss_StringWidth: width, stringHeight: height)
    }


  func ss_CGFloat() -> CGFloat
    {
        return CGFloat((self as NSString).doubleValue)
    }

/// Swift string ranges and NSString ranges are not compatible. For example, an emoji
/// like 😄 counts as one Swift character, but as two NSString characters (a so-called
/// UTF-16 surrogate pair)
/// http://stackoverflow.com/questions/25138339/nsrange-to-rangestring-index
   
    func swiftRange(fromNSRange nsRange: NSRange) -> Range<String.Index>?
    {
        guard
            let from16 = utf16.index(utf16.startIndex, offsetBy: nsRange.location, limitedBy: utf16.endIndex),
            let to16 = utf16.index(from16, offsetBy: nsRange.length, limitedBy: utf16.endIndex),
            let from = String.Index(from16, within: self),
            let to = String.Index(to16, within: self)
        else {
            return nil
        }
        return from ..< to
    }

}

public extension CGSize
{
	public init(ss_StringWidth width: String, stringHeight height: String)
    {
		self.init(width: width.ss_CGFloat(), height: height.ss_CGFloat())
	}
}


/// Returns the first string captured by the first Capture Group in the given pattern.
/// Returns nil if there was no match.

func SS_FirstCapture(forPattern pattern: String,
        inString string: String,
        regexOptions: NSRegularExpression.Options = [.dotMatchesLineSeparators])
         -> String?
{
    let regex = try! NSRegularExpression(pattern: pattern, options: regexOptions)
    if regex.numberOfCaptureGroups == 0 {
        print("ERROR: pattern argument doesn't contain a Capture Group! Exiting.")
        exit(EXIT_FAILURE)
    }
    
    guard let match = regex.firstMatch(in: string,
            options: [],
            range: NSMakeRange(0, string.characters.count)) else {
        
        // This is not an error.
        return nil
    }
    
    // Note: match.range is index 0, and represents the overall match.
    // match.rangeAtIndex(1) is the first Capture Group, (2) is the second, etc.
    
    let nsRange = match.rangeAt(1)
    if nsRange.location == NSNotFound {
        return nil
    }
        
    if let rangeIndex = string.swiftRange(fromNSRange: nsRange) {
        return string.substring(with: rangeIndex)
    } else {
        assert(false)
        return nil
    }
}

```
