### ISSUE TITLE
How to parse SVG content to UIImage

### ISSUE THREAD

**Issue by black-lotus** [pocketsvg/PocketSVG#83]
Is it possible to parse svg content to UIImage
I tried to find out in issues done, but still can't found what i was looking for

I have this svg string that i want to parse to uiimage

`<svg style="background:#fff" xmlns="http://www.w3.org/2000/svg" width="400" height="140" version="1.1"><line x1="20" x2="380" y1="120" y2="120" stroke="#b5b5b5" stroke-width="6" stroke-linecap="round" stroke-dasharray="0.2,30"/><polyline fill="none" stroke-width="2" stroke="#0bba7a" points="20,120 24.33734939759036,20 28.67469879518072,20 33.01204819277108,70 37.34939759036145,70 41.68674698795181,70 46.02409638554217,20 50.36144578313252,20 54.69879518072289,70 59.03614457831325,70 63.37349397590361,20 67.71084337349397,20 72.04819277108433,70 76.3855421686747,70 80.72289156626505,20 85.06024096385542,20 89.39759036144578,70 93.73493975903614,70 98.0722891566265,70 102.4096385542169,120 106.7469879518072,70 " /></svg>`

the result should be like this
![screen shot 2017-03-16 at 10 36 32 am](https://cloud.githubusercontent.com/assets/3261560/23980812/c396b2d0-0a34-11e7-9e21-3fcde17711b3.png)

Thank you in advance...

**Comment by fjolnir** [comment]
Simplest way would be to use an SVGLayer and use `renderInContext:`to draw it into a UIImage context created with `UIGraphicsBeginImageContext`.

**Comment by fjolnir** [comment]
Existing ticket: https://github.com/pocketsvg/PocketSVG/issues/71
