### ISSUE TITLE
Support rx/ry in rect element.

### ISSUE THREAD

**Issue by aaaron7** [pocketsvg/PocketSVG#85]
The SVG standard indicate that rect element has rx/ry property which implements rounded corner rect. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect.

PocketSVG seems directly turn rect into four points path when dealing with rect elements. doesn't support rounded corners.

Is there any plan to improve this part? Thanks.

**Comment by fjolnir** [comment]
Yep, that seems like something we should support, I'll try to get around to it soon.

**Comment by SuperWomble** [comment]
+1 Yes please! Thanks.
