### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by saoudrizwan** [pocketsvg/PocketSVG#87]
I'm trying to render this SVG file: www.bobbyapp.co/svg/ing.svg
But I keep getting this error:
```
*** Assertion failure in hexTriplet::hexTriplet(NSString *__strong)(), /Users/saoud/Bobby/Bobby2/Pods/PocketSVG/SVGEngine.mm:663

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: [str hasPrefix:@"#"]'
```
Any fixes? I tried compressing the SVG file using SVGO compressor but it only compressed by 1.5% and I'm still getting the issue. 

Any help would be greatly appreciated. 

Thanks

**Comment by SuperWomble** [comment]
It's choking on use of a color string literal "black" instead of hex color ("#000000").

As a workaround, replace:

`fill="#00000"`

with 

`fill="#000000"`

It will then draw without complaint.
