### ISSUE TITLE
not having colors when rendering the svg manually

### ISSUE THREAD

**Issue by namine92** [pocketsvg/PocketSVG#91]
Hi,
Well I'm facing an issue while trying to render the SVG manually, the "stroke" and "fill" attributes are always empty so those 2 lines: 

`    layer.strokeColor = [path.svgAttributes[@"stroke"] ?: [UIColor blackColor] CGColor];
    layer.fillColor   = [path.svgAttributes[@"fill"] ?: [UIColor redColor] CGColor];`

always gives the black and the red colour for every SVG.
So if someone can help me it will be nice.

**Comment by fjolnir** [comment]
what is the format of your svg's `stroke="..."` attribute?

**Comment by namine92** [comment]
Yes it's an hex triplets but when I debug the stroke and the fill values contains "(no summary)".

**Comment by fjolnir** [comment]
Please upload the problem svg

**Comment by namine92** [comment]
It's the svg of the demo project:
https://github.com/pocketsvg/PocketSVG/blob/master/Demos/Sample%20SVG%20Files/tiger.svg

**Comment by fjolnir** [comment]
Ah, the attributes contain a CGColorRef, not a UIColor. I just tested the tiger svg, and it is working fine with HEAD.

**Comment by namine92** [comment]
`    NSURL *url = [[NSBundle mainBundle] URLForResource:@"tiger" withExtension:@"svg"];

    for(SVGBezierPath *path in [SVGBezierPath pathsFromSVGAtURL:url]) {
        
        // Create a layer for each path
        CAShapeLayer *layer = [CAShapeLayer layer];
        layer.path = path.CGPath;
        
        // Set its display properties
        layer.lineWidth   = 4;
        
        layer.strokeColor = path.svgAttributes[@"stroke"] ?: UIColor.blackColor.CGColor;
        layer.fillColor = path.svgAttributes[@"fill"] ?: UIColor.redColor.CGColor;
        
        // Add it to the layer hierarchy
        [imgSGV.layer addSublayer:layer];
    }`
But now after I copied past your code I'm having a precompilation error : 
 Incompatible operand types ('id _Nullable' and 'CGColorRef _Nonnull' (aka 'struct CGColor *'))

**Comment by fjolnir** [comment]
sorry, `(__bridge CGColorRef)`

**Comment by namine92** [comment]
Thank you, it solved the error and I'm having the colours :)
