### ISSUE TITLE
some svg support advice

### ISSUE THREAD

**Issue by watermelon520** [pocketsvg/PocketSVG#93]
I'm Chinese developer.This lib is wonderful.To solve my some problem.But I found your support svg format are:` path,polygon,rect,ellipse,circle`.Why don't you support `polyline`.Although I found other ways to solve it。I hope you could support "polyline".By the way.I like this lib.

**Comment by fjolnir** [comment]
The need hadn't come up.

We'd welcome a patch adding support.

**Comment by fjolnir** [comment]
polyline support is in!
