### ISSUE TITLE
Can we convert  UIIImage from .svg image

### ISSUE THREAD

**Issue by tikamsingh** [pocketsvg/PocketSVG#98]

**Comment by arielelkin** [comment]
Hi @tikamsingh 

Sorry but it's not clear what exactly your question is. Could you please rephrase it?

**Comment by tikamsingh** [comment]
Let me explain:



1. UIImageView * pathFromImageView = [self createSVGImageFrom:self.shapeName imageView:shapeView tnitColor:[UIColor redColor] ];

2. (UIImageView *) createSVGImageFrom:(NSString *) svgName imageView:(UIImageView *) svgImageView tnitColor:(UIColor *)tintColor

{
NSURL *url = [[NSBundle mainBundle] URLForResource:svgName withExtension:@"svg"];
NSArray *pathArray = [SVGBezierPath pathsFromSVGAtURL:url];
CGRect pathRect = SVGBoundingRectForPaths(pathArray);
NSLog(@"pathRect %@",NSStringFromCGRect(pathRect));
for(SVGBezierPath *path in [SVGBezierPath pathsFromSVGAtURL:url]) {
// Create a layer for each path
CAShapeLayer *layer = [CAShapeLayer layer];
layer.path = path.CGPath;
layer.lineWidth = 2;
layer.strokeColor = [path.svgAttributes[@"stroke"] ?: tintColor CGColor];
layer.fillColor = [path.svgAttributes[@"fill"] ?: [UIColor clearColor] CGColor];
[svgImageView.layer addSublayer:layer];
}
return svgImageView;
}



3> UIImage *image = pathFromImageView.image ;

But image is not properly showing , It got cut some of the part.

**Comment by tikamsingh** [comment]
I am using this method to get the UIImage

+ (UIImage *) getCurrentImage: (UIImageView *)topView scale :(float) scale
{
    //scale = 0.0 for adder or eraser.
    // 1.0 for Effect
    UIGraphicsBeginImageContextWithOptions(topView.bounds.size, NO,  scale);

    //UIGraphicsBeginImageContext(topView.bounds.size);
    [topView.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage * img = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return  img;
}

But image is not properly showing , It got cut some of the part.

**Comment by fjolnir** [comment]
The functions you want are `SVGBoundingRectForPaths` and `SVGDrawPaths` in https://github.com/pocketsvg/PocketSVG/blob/master/SVGBezierPath.h#L16

Untested example code:
```objc
CGRect bounds = SVGBoundingRectForPaths(mySVGPaths);
UIGraphicsBeginImageContextWithOptions((CGSize) { CGRectGetMaxX(bounds), CGRectGetMaxY(bounds) }, NO, 0);
SVGDrawPaths(mySVGPaths, UIGraphicsGetCurrentContext(), bounds, nil, nil);
UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
```

**Comment by tikamsingh** [comment]
No ,Its not working. Actually I want to resize .svg image as a specific size .
I have .svg image with bounding box 24x24 . I want to contvert it in UIImage with 200x200 and display it in UIIImageView.


Can we do that.

**Comment by fjolnir** [comment]
Did you try changing the value of `bounds`?

**Comment by tikamsingh** [comment]
Yes , I was trying like this

NSURL *url = [[NSBundle mainBundle] URLForResource:svgName withExtension:@"svg"];
    NSArray *mySVGPaths =  [SVGBezierPath pathsFromSVGAtURL:url];

  //  CGRect bounds = SVGBoundingRectForPaths(mySVGPaths);
    CGSize size = CGSizeMake(200, 200);
    CGRect pathFrame = CGRectMake(0, 0, 200, 200);
    UIGraphicsBeginImageContextWithOptions(size, NO, 0);
    SVGDrawPaths(mySVGPaths, UIGraphicsGetCurrentContext(), pathFrame, nil, nil);
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return image;
