### ISSUE TITLE
Change sublayer fill color

### ISSUE THREAD

**Issue by GDGapps** [pocketsvg/PocketSVG#99]
Is it possible to change the fill color of a sublayer of the SVG file?
For example, can I change the fill color only of the layer called "IS-4" in the SVG named "iceland"?

Thank you!

**Comment by fjolnir** [comment]
You'll have to do that manually by finding that path based on it's `id` attribute after parsing and setting it's `fill` attribute to a `CGColorRef`.

**Comment by GDGapps** [comment]
I'm really sorry to bother you, but I'm not able to do that successfully. In particular, I'm not able to properly place the resulting CAShapeLayer in a View.

This is my code:

`override func viewDidLoad() {
        super.viewDidLoad()
        
        let url = Bundle.main.url(forResource: "iceland", withExtension: "svg")!
        
        let tP:SVGBezierPath = SVGBezierPath()
        for path in SVGBezierPath.pathsFromSVG(at: url) {
            
            
            let layer:CAShapeLayer = CAShapeLayer()
            layer.path = path.cgPath
            
            if path.svgAttributes["id"] as! String == "IS-4" {
            
                layer.fillColor = UIColor.red.cgColor
            }
            tP.append(path)
            
            self.icelandShape.addSublayer(layer)
        }
        self.boundingBox = tP.cgPath.boundingBox
        

        let boundingBoxAspectRatio = self.boundingBox!.width/self.boundingBox!.height
        let viewAspectRatio = self.rView.frame.width/self.rView.frame.height
        
        if (boundingBoxAspectRatio > viewAspectRatio) {
            // Width is limiting factor
            self.scaleFactor = self.rView.frame.width/boundingBox!.width
        } else {
            // Height is limiting factor
            self.scaleFactor = self.rView.frame.height/boundingBox!.height
        }

        let scaleTransform = CATransform3DMakeScale(scaleFactor!, scaleFactor!, 1.0)
        
        self.icelandShape.transform = scaleTransform
        
        self.view.layer.addSublayer(icelandShape)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        self.icelandShape.frame = self.rView.bounds
        self.icelandShape.position = self.rView.center
    }`

But the result is odd.

![simulator screen shot 16 ago 2017 15 40 40](https://user-images.githubusercontent.com/11598969/29366681-f25a0458-829a-11e7-97ce-92cd4e78f874.png)

What did I do wrong?
Is there a better way to display the SVG (like aspectFit) after you prepare it manually?

Thank you very much

**Comment by fjolnir** [comment]
Why don't you just use an SVGLayer?

**Comment by GDGapps** [comment]
Do you mean to add a sublayer to a view as a SVGLayer? or using SVGImageView?
If I use SVGImageView I can't access sublayers to colour a specific layer of  the SVG. If I parse it through SVGBezierPath.pathsFromSVG(at: url) how can I use SVGLayer? If I add CAShapeLayers to a SVGLayer it behaves like a CALayer, it doesn't seem  to change anything.

I also have problems with AspectFit using SVGImageView. If for example i set in the demo app the SVGName as "Circle" the result is this one (with AspectFit)..

![schermata 2017-08-16 alle 22 43 05](https://user-images.githubusercontent.com/11598969/29384594-f3fccbf8-82d4-11e7-8e62-0af271022d76.png)

Thank you

**Comment by fjolnir** [comment]
I just pushed changes to make this easier, now you can do:

```swift
let svgView = SVGImageView.init(contentsOf: url)
svgView.paths = svgView.paths.map { (path) in
	if path.svgAttributes["id"] as? String == "IS-4" {
		return path.settingSVGAttributes(["fill": UIColor.red.cgColor])
	} else {
		return path
	}
}
```

**Comment by GDGapps** [comment]
Everything works now.
Thank you very very much!
